import {
  AblrSVG,
  AblrV1ROU,
  AblrV1SQU,
  AblrV2ROU,
  AblrV2SQU,
  AEONBankSVG,
  AEONBankV1BSQU,
  AEONBankV1LG,
  AEONBankV1ROU,
  AEONBankV1SQU,
  AEONBankV2BSQU,
  AEONBankV2LG,
  AEONBankV2ROU,
  AEONBankV2SQU,
  AffinBankSVG,
  AffinBankV1BSQU,
  AffinBankV1LG,
  AffinBankV1ROU,
  AffinBankV1SQU,
  AffinBankV2BSQU,
  AffinBankV2LG,
  AffinBankV2ROU,
  AffinBankV2SQU,
  AgroBankSVG,
  AgroBankV1BSQU,
  AgroBankV1LG,
  AgroBankV1ROU,
  AgroBankV1SQU,
  AlipaySVG,
  AlipayV1ROU,
  AlipayV1SQU,
  AlipayV2ROU,
  AlipayV2SQU,
  AlipayPlusSVG,
  AlipayPlusV1ROU,
  AlipayPlusV1SQU,
  AlipayPlusV2ROU,
  AlipayPlusV2SQU,
  AllianceBankSVG,
  AllianceBankV1BSQU,
  AllianceBankV1LG,
  AllianceBankV1ROU,
  AllianceBankV1SQU,
  AmBankSVG,
  AmBankV1BSQU,
  AmBankV1LG,
  AmBankV1ROU,
  AmBankV1SQU,
  AmBankV2BSQU,
  AmBankV2LG,
  AmBankV2ROU,
  AmBankV2SQU,
  AmBankV3BSQU,
  AmBankV3LG,
  AmBankV3ROU,
  AmBankV3SQU,
  AmBankV4BSQU,
  AmBankV4LG,
  AmBankV5BSQU,
  AmBankV5LG,
  ApplePaySVG,
  ApplePayV1ROU,
  ApplePayV1SQU,
  ApplePayV1TRSP,
  ApplePayV2ROU,
  ApplePayV2SQU,
  ApplePayV2TRSP,
  AtomeSVG,
  AtomeV1ROU,
  AtomeV1SQU,
  AtomeV2ROU,
  AtomeV2SQU,
  AtomeV3LG,
  AtomeV3ROU,
  AtomeV3ROUCopy,
  AtomeV3SQU,
  AtomeV3SQUCopy,
  AtomeV4LG,
  AtomeV4ROU,
  AtomeV4SQU,
  BankIslamSVG,
  BankIslamV1BSQU,
  BankIslamV1LG,
  BankIslamV1ROU,
  BankIslamV1SQU,
  BankMuamalatSVG,
  BankMuamalatV1BSQU,
  BankMuamalatV1LG,
  BankMuamalatV1ROU,
  BankMuamalatV1SQU,
  BankMuamalatV2BSQU,
  BankMuamalatV2LG,
  BankMuamalatV2ROU,
  BankMuamalatV2SQU,
  BankMuamalatV3ROU,
  BankMuamalatV3SQU,
  BankMuamalatV4ROU,
  BankMuamalatV4SQU,
  BankOfChinaSVG,
  BankOfChinaV1BSQU,
  BankOfChinaV1LG,
  BankOfChinaV1ROU,
  BankOfChinaV1SQU,
  BankRakyatSVG,
  BankRakyatV1BSQU,
  BankRakyatV1LG,
  BankRakyatV1ROU,
  BankRakyatV1SQU,
  BankRakyatV2BSQU,
  BankRakyatV2LG,
  BankRakyatV2ROU,
  BankRakyatV2SQU,
  BinfiniteSVG,
  BinfiniteV1ROU,
  BinfiniteV1SQU,
  BinfiniteV2ROU,
  BinfiniteV2SQU,
  BinfiniteV3ROU,
  BinfiniteV3SQU,
  BNPParibasBankSVG,
  BNPParibasBankV1BSQU,
  BNPParibasBankV1LG,
  BNPParibasBankV1ROU,
  BNPParibasBankV1SQU,
  BNPParibasBankV2BSQU,
  BNPParibasBankV2LG,
  BNPParibasBankV2ROU,
  BNPParibasBankV2SQU,
  BoostSVG,
  BoostV1ROU,
  BoostV1SQU,
  BoostV2ROU,
  BoostV2SQU,
  BoostV3ROU,
  BoostV3SQU,
  BoostBankSVG,
  BoostBankV1BSQU,
  BoostBankV1LG,
  BoostBankV1ROU,
  BoostBankV1SQU,
  BSNSVG,
  BSNV1BSQU,
  BSNV1LG,
  BSNV1ROU,
  BSNV1SQU,
  CardSVG,
  CardV1ROU,
  CardV1SQU,
  CimbSVG,
  CimbV1BSQU,
  CimbV1LG,
  CimbV1ROU,
  CimbV1SQU,
  CimbV2BSQU,
  CimbV2LG,
  CimbV2ROU,
  CimbV2SQU,
  CimbV3BSQU,
  CimbV3LG,
  CimbV3ROU,
  CimbV3SQU,
  CimbV4BSQU,
  CimbV4LG,
  CimbV5LG,
  CitiBankSVG,
  CitiBankV1BSQU,
  CitiBankV1LG,
  CitiBankV1ROU,
  CitiBankV1SQU,
  CitiBankV2BSQU,
  CitiBankV2LG,
  CitiBankV2ROU,
  CitiBankV2SQU,
  DeutscheBankSVG,
  DeutscheBankV1BSQU,
  DeutscheBankV1LG,
  DeutscheBankV1ROU,
  DeutscheBankV1SQU,
  DeutscheBankV2BSQU,
  DeutscheBankV2LG,
  DeutscheBankV2ROU,
  DeutscheBankV2SQU,
  DuitNowSVG,
  DuitNowV1ROU,
  DuitNowV1SQU,
  DuitNowV2ROU,
  DuitNowV2SQU,
  DuitNowV3ROU,
  DuitNowV3SQU,
  DuitNowV4ROU,
  DuitNowV4SQU,
  FavePaySVG,
  FavePayV1ROU,
  FavePayV1SQU,
  FavePayV2ROU,
  FavePayV2SQU,
  FPXSVG,
  FPXV1ROU,
  FPXV1SQU,
  FPXV2ROU,
  FPXV2SQU,
  FPXV3ROU,
  FPXV3SQU,
  GobizSVG,
  GobizV1ROU,
  GobizV1SQU,
  GobizV2ROU,
  GobizV2SQU,
  GooglePaySVG,
  GooglePayV1ROU,
  GooglePayV1SQU,
  GooglePayV1TRSP,
  GooglePayV2ROU,
  GooglePayV2SQU,
  GooglePayV2TRSP,
  GooglePayV3ROU,
  GooglePayV3SQU,
  GooglePayV3TRSP,
  GoPayzSVG,
  GoPayzV1ROU,
  GoPayzV1SQU,
  GoPayzV2ROU,
  GoPayzV2SQU,
  GrabPaySVG,
  GrabPayV1ROU,
  GrabPayV1SQU,
  GrabPayV2ROU,
  GrabPayV2SQU,
  GrabPayV3ROU,
  GrabPayV3SQU,
  GrabPayV4ROU,
  GrabPayV4SQU,
  GrabPayLaterSVG,
  GrabPayLaterV1LG,
  GrabPayLaterV2LG,
  GXBankSVG,
  GXBankV1BSQU,
  GXBankV1LG,
  GXBankV1ROU,
  GXBankV1SQU,
  GXBankV2BSQU,
  GXBankV2LG,
  GXBankV2ROU,
  GXBankV2SQU,
  GXBankV3BSQU,
  GXBankV3LG,
  GXBankV3ROU,
  GXBankV3SQU,
  GXBankV4BSQU,
  GXBankV4LG,
  GXBankV4ROU,
  GXBankV4SQU,
  GXBankV5BSQU,
  GXBankV5LG,
  GXBankV5ROU,
  GXBankV5SQU,
  HongLeongBankSVG,
  HongLeongBankV1BSQU,
  HongLeongBankV1LG,
  HongLeongBankV1ROU,
  HongLeongBankV1SQU,
  HongLeongBankV2BSQU,
  HongLeongBankV2LG,
  HSBCSVG,
  HSBCV1BSQU,
  HSBCV1LG,
  HSBCV1ROU,
  HSBCV1SQU,
  IOUPaySVG,
  IOUPayV1ROU,
  IOUPayV1SQU,
  IOUPayV2ROU,
  IOUPayV2SQU,
  KuwaitFinanceHouseSVG,
  KuwaitFinanceHouseV1BSQU,
  KuwaitFinanceHouseV1LG,
  KuwaitFinanceHouseV1ROU,
  KuwaitFinanceHouseV1SQU,
  KuwaitFinanceHouseV2BSQU,
  KuwaitFinanceHouseV2LG,
  KuwaitFinanceHouseV2ROU,
  KuwaitFinanceHouseV2SQU,
  LazadaSVG,
  LazadaV1ROU,
  LazadaV1SQU,
  LazadaV2ROU,
  LazadaV2SQU,
  MAESVG,
  MAEV1ROU,
  MAEV1SQU,
  MASTERSVG,
  MASTERV1ROU,
  MASTERV1SQU,
  MASTERV1TRSP,
  MASTERV2ROU,
  MASTERV2SQU,
  MASTERV3ROU,
  MASTERV3SQU,
  MASTERV4ROU,
  MASTERV4SQU,
  MayBankV1BSQU,
  MayBankV1LG,
  MayBankV1ROU,
  MayBankV1SQU,
  MaybankQRV1ROU,
  MaybankQRV1SQU,
  MBSBSVG,
  MBSBV1BSQU,
  MBSBV1LG,
  MBSBV1ROU,
  MBSBV1SQU,
  MCashSVG,
  MCashV1ROU,
  MCashV1SQU,
  MCashV2ROU,
  MCashV2SQU,
  NetsPaySVG,
  NetsPayV1ROU,
  NetsPayV1SQU,
  OCBCSVG,
  OCBCV1BSQU,
  OCBCV1LG,
  OCBCV1ROU,
  OCBCV1SQU,
  OCBCV2BSQU,
  OCBCV2LG,
  OCBCV2ROU,
  OCBCV2SQU,
  PaydeeSVG,
  PaydeeV1ROU,
  PaydeeV1SQU,
  PaydeeV2ROU,
  PaydeeV2SQU,
  PrestoSVG,
  PrestoV1ROU,
  PrestoV1SQU,
  PrestoV2ROU,
  PrestoV2SQU,
  PrestoV3ROU,
  PrestoV3SQU,
  PrestoV4ROU,
  PrestoV4SQU,
  PrestoV5ROU,
  PrestoV5SQU,
  PublicBankSVG,
  PublicBankV1BSQU,
  PublicBankV1LG,
  PublicBankV1ROU,
  PublicBankV1SQU,
  RazerPaySVG,
  RazerPayV1ROU,
  RazerPayV1SQU,
  RHBSVG,
  RHBV1BSQU,
  RHBV1LG,
  RHBV1ROU,
  RHBV1SQU,
  RHBV2BSQU,
  RHBV2LG,
  RHBV2ROU,
  RHBV2SQU,
  RytBankSVG,
  RytBankV1BSQU,
  RytBankV1LG,
  RytBankV1ROU,
  RytBankV1SQU,
  RytBankV2BSQU,
  RytBankV2LG,
  RytBankV2ROU,
  RytBankV2SQU,
  SamsungPaySVG,
  SamsungPayV1ROU,
  SamsungPayV1SQU,
  SamsungPayV2ROU,
  SamsungPayV2SQU,
  SamsungPayV3ROU,
  SamsungPayV3SQU,
  SarawakPaySVG,
  SarawakPayV1ROU,
  SarawakPayV1SQU,
  SarawakPayV2ROU,
  SarawakPayV2SQU,
  SenhengSVG,
  SenhengV1ROU,
  SenhengV1SQU,
  SenhengV2ROU,
  SenhengV2SQU,
  SetelSVG,
  SetelV1ROU,
  SetelV1SQU,
  SetelV2ROU,
  SetelV2SQU,
  SetelV3SQU,
  ShopBackSVG,
  ShopBackV1ROU,
  ShopBackV1SQU,
  ShopBackV2ROU,
  ShopBackV2SQU,
  ShopeePaySVG,
  ShopeePayV1ROU,
  ShopeePayV1SQU,
  ShopeePayV2ROU,
  ShopeePayV2SQU,
  ShopeePayV3ROU,
  ShopeePayV3SQU,
  ShopeePayV4ROU,
  ShopeePayV4SQU,
  ShopeePayV5ROU,
  ShopeePayV5SQU,
  ShopeePayV6ROU,
  ShopeePayV6SQU,
  SPayLaterSVG,
  SPayLaterV1LG,
  SPayLaterV1ROU,
  SPayLaterV1SQU,
  SPayLaterV2LG,
  SPayLaterV2ROU,
  SPayLaterV2SQU,
  SplitSVG,
  SplitV1ROU,
  SplitV1SQU,
  SplitV2ROU,
  SplitV2SQU,
  SplitV3ROU,
  SplitV3SQU,
  SplitV4ROU,
  SplitV4SQU,
  StandardCharteredSVG,
  StandardCharteredV1BSQU,
  StandardCharteredV1LG,
  StandardCharteredV1ROU,
  StandardCharteredV1SQU,
  TaPaySVG,
  TaPayV1ROU,
  TaPayV1SQU,
  TaPayV2ROU,
  TaPayV2SQU,
  TNGSVG,
  TNGV1ROU,
  TNGV1SQU,
  TNGV2ROU,
  TNGV2SQU,
  TNGV2SVG,
  TruemoneySVG,
  TruemoneyV1ROU,
  TruemoneyV1SQU,
  TruemoneyV2ROU,
  TruemoneyV2SQU,
  UNIONPAYSVG,
  UNIONPAYV1ROU,
  UNIONPAYV1SQU,
  UNIONPAYV1TRSP,
  UOBSVG,
  UOBV1BSQU,
  UOBV1LG,
  UOBV1ROU,
  UOBV1SQU,
  UOBV2BSQU,
  UOBV2LG,
  UOBV2ROU,
  UOBV2SQU,
  UOBV3ROU,
  UOBV3SQU,
  UOBV4ROU,
  UOBV4SQU,
  VISASVG,
  VISAV1ROU,
  VISAV1SQU,
  VISAV1TRSP,
  VISAV2ROU,
  VISAV2SQU,
  VISAV2TRSP,
  WeChatSVG,
  WeChatV1ROU,
  WeChatV1SQU,
  WeChatV2ROU,
  WeChatV2SQU,
  WeChatV3ROU,
  WeChatV3SQU,
  ZappSVG,
  ZappV1ROU,
  ZappV1SQU,
} from "@raufsemi/myicons";

export const icons = [
  {
    name: "Ablr SVG",
    slug: "ablr-svg",
    category: "BNPL",
    componentName: "AblrSVG",
    component: AblrSVG,
  },
  {
    name: "Ablr V1 ROU",
    slug: "ablr-v1-rou",
    category: "BNPL",
    componentName: "AblrV1ROU",
    component: AblrV1ROU,
  },
  {
    name: "Ablr V1 SQU",
    slug: "ablr-v1-squ",
    category: "BNPL",
    componentName: "AblrV1SQU",
    component: AblrV1SQU,
  },
  {
    name: "Ablr V2 ROU",
    slug: "ablr-v2-rou",
    category: "BNPL",
    componentName: "AblrV2ROU",
    component: AblrV2ROU,
  },
  {
    name: "Ablr V2 SQU",
    slug: "ablr-v2-squ",
    category: "BNPL",
    componentName: "AblrV2SQU",
    component: AblrV2SQU,
  },
  {
    name: "AEONBank SVG",
    slug: "aeonbank-svg",
    category: "Banks",
    componentName: "AEONBankSVG",
    component: AEONBankSVG,
  },
  {
    name: "AEONBank V1 BSQU",
    slug: "aeonbank-v1-bsqu",
    category: "Banks",
    componentName: "AEONBankV1BSQU",
    component: AEONBankV1BSQU,
  },
  {
    name: "AEONBank V1 LG",
    slug: "aeonbank-v1-lg",
    category: "Banks",
    componentName: "AEONBankV1LG",
    component: AEONBankV1LG,
  },
  {
    name: "AEONBank V1 ROU",
    slug: "aeonbank-v1-rou",
    category: "Banks",
    componentName: "AEONBankV1ROU",
    component: AEONBankV1ROU,
  },
  {
    name: "AEONBank V1 SQU",
    slug: "aeonbank-v1-squ",
    category: "Banks",
    componentName: "AEONBankV1SQU",
    component: AEONBankV1SQU,
  },
  {
    name: "AEONBank V2 BSQU",
    slug: "aeonbank-v2-bsqu",
    category: "Banks",
    componentName: "AEONBankV2BSQU",
    component: AEONBankV2BSQU,
  },
  {
    name: "AEONBank V2 LG",
    slug: "aeonbank-v2-lg",
    category: "Banks",
    componentName: "AEONBankV2LG",
    component: AEONBankV2LG,
  },
  {
    name: "AEONBank V2 ROU",
    slug: "aeonbank-v2-rou",
    category: "Banks",
    componentName: "AEONBankV2ROU",
    component: AEONBankV2ROU,
  },
  {
    name: "AEONBank V2 SQU",
    slug: "aeonbank-v2-squ",
    category: "Banks",
    componentName: "AEONBankV2SQU",
    component: AEONBankV2SQU,
  },
  {
    name: "AffinBank SVG",
    slug: "affin-bank-svg",
    category: "Banks",
    componentName: "AffinBankSVG",
    component: AffinBankSVG,
  },
  {
    name: "AffinBank V1 BSQU",
    slug: "affin-bank-v1-bsqu",
    category: "Banks",
    componentName: "AffinBankV1BSQU",
    component: AffinBankV1BSQU,
  },
  {
    name: "AffinBank V1 LG",
    slug: "affin-bank-v1-lg",
    category: "Banks",
    componentName: "AffinBankV1LG",
    component: AffinBankV1LG,
  },
  {
    name: "AffinBank V1 ROU",
    slug: "affin-bank-v1-rou",
    category: "Banks",
    componentName: "AffinBankV1ROU",
    component: AffinBankV1ROU,
  },
  {
    name: "AffinBank V1 SQU",
    slug: "affin-bank-v1-squ",
    category: "Banks",
    componentName: "AffinBankV1SQU",
    component: AffinBankV1SQU,
  },
  {
    name: "AffinBank V2 BSQU",
    slug: "affin-bank-v2-bsqu",
    category: "Banks",
    componentName: "AffinBankV2BSQU",
    component: AffinBankV2BSQU,
  },
  {
    name: "AffinBank V2 LG",
    slug: "affin-bank-v2-lg",
    category: "Banks",
    componentName: "AffinBankV2LG",
    component: AffinBankV2LG,
  },
  {
    name: "AffinBank V2 ROU",
    slug: "affin-bank-v2-rou",
    category: "Banks",
    componentName: "AffinBankV2ROU",
    component: AffinBankV2ROU,
  },
  {
    name: "AffinBank V2 SQU",
    slug: "affin-bank-v2-squ",
    category: "Banks",
    componentName: "AffinBankV2SQU",
    component: AffinBankV2SQU,
  },
  {
    name: "AgroBank SVG",
    slug: "agro-bank-svg",
    category: "Banks",
    componentName: "AgroBankSVG",
    component: AgroBankSVG,
  },
  {
    name: "AgroBank V1 BSQU",
    slug: "agro-bank-v1-bsqu",
    category: "Banks",
    componentName: "AgroBankV1BSQU",
    component: AgroBankV1BSQU,
  },
  {
    name: "AgroBank V1 LG",
    slug: "agro-bank-v1-lg",
    category: "Banks",
    componentName: "AgroBankV1LG",
    component: AgroBankV1LG,
  },
  {
    name: "AgroBank V1 ROU",
    slug: "agro-bank-v1-rou",
    category: "Banks",
    componentName: "AgroBankV1ROU",
    component: AgroBankV1ROU,
  },
  {
    name: "AgroBank V1 SQU",
    slug: "agro-bank-v1-squ",
    category: "Banks",
    componentName: "AgroBankV1SQU",
    component: AgroBankV1SQU,
  },
  {
    name: "Alipay SVG",
    slug: "alipay-svg",
    category: "Wallet",
    componentName: "AlipaySVG",
    component: AlipaySVG,
  },
  {
    name: "Alipay V1 ROU",
    slug: "alipay-v1-rou",
    category: "Wallet",
    componentName: "AlipayV1ROU",
    component: AlipayV1ROU,
  },
  {
    name: "Alipay V1 SQU",
    slug: "alipay-v1-squ",
    category: "Wallet",
    componentName: "AlipayV1SQU",
    component: AlipayV1SQU,
  },
  {
    name: "Alipay V2 ROU",
    slug: "alipay-v2-rou",
    category: "Wallet",
    componentName: "AlipayV2ROU",
    component: AlipayV2ROU,
  },
  {
    name: "Alipay V2 SQU",
    slug: "alipay-v2-squ",
    category: "Wallet",
    componentName: "AlipayV2SQU",
    component: AlipayV2SQU,
  },
  {
    name: "AlipayPlus SVG",
    slug: "alipay-plus-svg",
    category: "Wallet",
    componentName: "AlipayPlusSVG",
    component: AlipayPlusSVG,
  },
  {
    name: "AlipayPlus V1 ROU",
    slug: "alipay-plus-v1-rou",
    category: "Wallet",
    componentName: "AlipayPlusV1ROU",
    component: AlipayPlusV1ROU,
  },
  {
    name: "AlipayPlus V1 SQU",
    slug: "alipay-plus-v1-squ",
    category: "Wallet",
    componentName: "AlipayPlusV1SQU",
    component: AlipayPlusV1SQU,
  },
  {
    name: "AlipayPlus V2 ROU",
    slug: "alipay-plus-v2-rou",
    category: "Wallet",
    componentName: "AlipayPlusV2ROU",
    component: AlipayPlusV2ROU,
  },
  {
    name: "AlipayPlus V2 SQU",
    slug: "alipay-plus-v2-squ",
    category: "Wallet",
    componentName: "AlipayPlusV2SQU",
    component: AlipayPlusV2SQU,
  },
  {
    name: "AllianceBank SVG",
    slug: "alliance-bank-svg",
    category: "Banks",
    componentName: "AllianceBankSVG",
    component: AllianceBankSVG,
  },
  {
    name: "AllianceBank V1 BSQU",
    slug: "alliance-bank-v1-bsqu",
    category: "Banks",
    componentName: "AllianceBankV1BSQU",
    component: AllianceBankV1BSQU,
  },
  {
    name: "AllianceBank V1 LG",
    slug: "alliance-bank-v1-lg",
    category: "Banks",
    componentName: "AllianceBankV1LG",
    component: AllianceBankV1LG,
  },
  {
    name: "AllianceBank V1 ROU",
    slug: "alliance-bank-v1-rou",
    category: "Banks",
    componentName: "AllianceBankV1ROU",
    component: AllianceBankV1ROU,
  },
  {
    name: "AllianceBank V1 SQU",
    slug: "alliance-bank-v1-squ",
    category: "Banks",
    componentName: "AllianceBankV1SQU",
    component: AllianceBankV1SQU,
  },
  {
    name: "AmBank SVG",
    slug: "am-bank-svg",
    category: "Banks",
    componentName: "AmBankSVG",
    component: AmBankSVG,
  },
  {
    name: "AmBank V1 BSQU",
    slug: "am-bank-v1-bsqu",
    category: "Banks",
    componentName: "AmBankV1BSQU",
    component: AmBankV1BSQU,
  },
  {
    name: "AmBank V1 LG",
    slug: "am-bank-v1-lg",
    category: "Banks",
    componentName: "AmBankV1LG",
    component: AmBankV1LG,
  },
  {
    name: "AmBank V1 ROU",
    slug: "am-bank-v1-rou",
    category: "Banks",
    componentName: "AmBankV1ROU",
    component: AmBankV1ROU,
  },
  {
    name: "AmBank V1 SQU",
    slug: "am-bank-v1-squ",
    category: "Banks",
    componentName: "AmBankV1SQU",
    component: AmBankV1SQU,
  },
  {
    name: "AmBank V2 BSQU",
    slug: "am-bank-v2-bsqu",
    category: "Banks",
    componentName: "AmBankV2BSQU",
    component: AmBankV2BSQU,
  },
  {
    name: "AmBank V2 LG",
    slug: "am-bank-v2-lg",
    category: "Banks",
    componentName: "AmBankV2LG",
    component: AmBankV2LG,
  },
  {
    name: "AmBank V2 ROU",
    slug: "am-bank-v2-rou",
    category: "Banks",
    componentName: "AmBankV2ROU",
    component: AmBankV2ROU,
  },
  {
    name: "AmBank V2 SQU",
    slug: "am-bank-v2-squ",
    category: "Banks",
    componentName: "AmBankV2SQU",
    component: AmBankV2SQU,
  },
  {
    name: "AmBank V3 BSQU",
    slug: "am-bank-v3-bsqu",
    category: "Banks",
    componentName: "AmBankV3BSQU",
    component: AmBankV3BSQU,
  },
  {
    name: "AmBank V3 LG",
    slug: "am-bank-v3-lg",
    category: "Banks",
    componentName: "AmBankV3LG",
    component: AmBankV3LG,
  },
  {
    name: "AmBank V3 ROU",
    slug: "am-bank-v3-rou",
    category: "Banks",
    componentName: "AmBankV3ROU",
    component: AmBankV3ROU,
  },
  {
    name: "AmBank V3 SQU",
    slug: "am-bank-v3-squ",
    category: "Banks",
    componentName: "AmBankV3SQU",
    component: AmBankV3SQU,
  },
  {
    name: "AmBank V4 BSQU",
    slug: "am-bank-v4-bsqu",
    category: "Banks",
    componentName: "AmBankV4BSQU",
    component: AmBankV4BSQU,
  },
  {
    name: "AmBank V4 LG",
    slug: "am-bank-v4-lg",
    category: "Banks",
    componentName: "AmBankV4LG",
    component: AmBankV4LG,
  },
  {
    name: "AmBank V5 BSQU",
    slug: "am-bank-v5-bsqu",
    category: "Banks",
    componentName: "AmBankV5BSQU",
    component: AmBankV5BSQU,
  },
  {
    name: "AmBank V5 LG",
    slug: "am-bank-v5-lg",
    category: "Banks",
    componentName: "AmBankV5LG",
    component: AmBankV5LG,
  },
  {
    name: "ApplePay SVG",
    slug: "apple-pay-svg",
    category: "Mobile",
    componentName: "ApplePaySVG",
    component: ApplePaySVG,
  },
  {
    name: "ApplePay V1 ROU",
    slug: "apple-pay-v1-rou",
    category: "Mobile",
    componentName: "ApplePayV1ROU",
    component: ApplePayV1ROU,
  },
  {
    name: "ApplePay V1 SQU",
    slug: "apple-pay-v1-squ",
    category: "Mobile",
    componentName: "ApplePayV1SQU",
    component: ApplePayV1SQU,
  },
  {
    name: "ApplePay V1 TRSP",
    slug: "apple-pay-v1-trsp",
    category: "Mobile",
    componentName: "ApplePayV1TRSP",
    component: ApplePayV1TRSP,
  },
  {
    name: "ApplePay V2 ROU",
    slug: "apple-pay-v2-rou",
    category: "Mobile",
    componentName: "ApplePayV2ROU",
    component: ApplePayV2ROU,
  },
  {
    name: "ApplePay V2 SQU",
    slug: "apple-pay-v2-squ",
    category: "Mobile",
    componentName: "ApplePayV2SQU",
    component: ApplePayV2SQU,
  },
  {
    name: "ApplePay V2 TRSP",
    slug: "apple-pay-v2-trsp",
    category: "Mobile",
    componentName: "ApplePayV2TRSP",
    component: ApplePayV2TRSP,
  },
  {
    name: "Atome SVG",
    slug: "atome-svg",
    category: "BNPL",
    componentName: "AtomeSVG",
    component: AtomeSVG,
  },
  {
    name: "Atome V1 ROU",
    slug: "atome-v1-rou",
    category: "BNPL",
    componentName: "AtomeV1ROU",
    component: AtomeV1ROU,
  },
  {
    name: "Atome V1 SQU",
    slug: "atome-v1-squ",
    category: "BNPL",
    componentName: "AtomeV1SQU",
    component: AtomeV1SQU,
  },
  {
    name: "Atome V2 ROU",
    slug: "atome-v2-rou",
    category: "BNPL",
    componentName: "AtomeV2ROU",
    component: AtomeV2ROU,
  },
  {
    name: "Atome V2 SQU",
    slug: "atome-v2-squ",
    category: "BNPL",
    componentName: "AtomeV2SQU",
    component: AtomeV2SQU,
  },
  {
    name: "Atome V3 LG",
    slug: "atome-v3-lg",
    category: "BNPL",
    componentName: "AtomeV3LG",
    component: AtomeV3LG,
  },
  {
    name: "Atome V3 ROU",
    slug: "atome-v3-rou",
    category: "BNPL",
    componentName: "AtomeV3ROU",
    component: AtomeV3ROU,
  },
  {
    name: "Atome V3 ROU Copy",
    slug: "atome-v3-rou-copy",
    category: "BNPL",
    componentName: "AtomeV3ROUCopy",
    component: AtomeV3ROUCopy,
  },
  {
    name: "Atome V3 SQU",
    slug: "atome-v3-squ",
    category: "BNPL",
    componentName: "AtomeV3SQU",
    component: AtomeV3SQU,
  },
  {
    name: "Atome V3 SQU Copy",
    slug: "atome-v3-squ-copy",
    category: "BNPL",
    componentName: "AtomeV3SQUCopy",
    component: AtomeV3SQUCopy,
  },
  {
    name: "Atome V4 LG",
    slug: "atome-v4-lg",
    category: "BNPL",
    componentName: "AtomeV4LG",
    component: AtomeV4LG,
  },
  {
    name: "Atome V4 ROU",
    slug: "atome-v4-rou",
    category: "BNPL",
    componentName: "AtomeV4ROU",
    component: AtomeV4ROU,
  },
  {
    name: "Atome V4 SQU",
    slug: "atome-v4-squ",
    category: "BNPL",
    componentName: "AtomeV4SQU",
    component: AtomeV4SQU,
  },
  {
    name: "BankIslam SVG",
    slug: "bank-islam-svg",
    category: "Banks",
    componentName: "BankIslamSVG",
    component: BankIslamSVG,
  },
  {
    name: "BankIslam V1 BSQU",
    slug: "bank-islam-v1-bsqu",
    category: "Banks",
    componentName: "BankIslamV1BSQU",
    component: BankIslamV1BSQU,
  },
  {
    name: "BankIslam V1 LG",
    slug: "bank-islam-v1-lg",
    category: "Banks",
    componentName: "BankIslamV1LG",
    component: BankIslamV1LG,
  },
  {
    name: "BankIslam V1 ROU",
    slug: "bank-islam-v1-rou",
    category: "Banks",
    componentName: "BankIslamV1ROU",
    component: BankIslamV1ROU,
  },
  {
    name: "BankIslam V1 SQU",
    slug: "bank-islam-v1-squ",
    category: "Banks",
    componentName: "BankIslamV1SQU",
    component: BankIslamV1SQU,
  },
  {
    name: "BankMuamalat SVG",
    slug: "bank-muamalat-svg",
    category: "Banks",
    componentName: "BankMuamalatSVG",
    component: BankMuamalatSVG,
  },
  {
    name: "BankMuamalat V1 BSQU",
    slug: "bank-muamalat-v1-bsqu",
    category: "Banks",
    componentName: "BankMuamalatV1BSQU",
    component: BankMuamalatV1BSQU,
  },
  {
    name: "BankMuamalat V1 LG",
    slug: "bank-muamalat-v1-lg",
    category: "Banks",
    componentName: "BankMuamalatV1LG",
    component: BankMuamalatV1LG,
  },
  {
    name: "BankMuamalat V1 ROU",
    slug: "bank-muamalat-v1-rou",
    category: "Banks",
    componentName: "BankMuamalatV1ROU",
    component: BankMuamalatV1ROU,
  },
  {
    name: "BankMuamalat V1 SQU",
    slug: "bank-muamalat-v1-squ",
    category: "Banks",
    componentName: "BankMuamalatV1SQU",
    component: BankMuamalatV1SQU,
  },
  {
    name: "BankMuamalat V2 BSQU",
    slug: "bank-muamalat-v2-bsqu",
    category: "Banks",
    componentName: "BankMuamalatV2BSQU",
    component: BankMuamalatV2BSQU,
  },
  {
    name: "BankMuamalat V2 LG",
    slug: "bank-muamalat-v2-lg",
    category: "Banks",
    componentName: "BankMuamalatV2LG",
    component: BankMuamalatV2LG,
  },
  {
    name: "BankMuamalat V2 ROU",
    slug: "bank-muamalat-v2-rou",
    category: "Banks",
    componentName: "BankMuamalatV2ROU",
    component: BankMuamalatV2ROU,
  },
  {
    name: "BankMuamalat V2 SQU",
    slug: "bank-muamalat-v2-squ",
    category: "Banks",
    componentName: "BankMuamalatV2SQU",
    component: BankMuamalatV2SQU,
  },
  {
    name: "BankMuamalat V3 ROU",
    slug: "bank-muamalat-v3-rou",
    category: "Banks",
    componentName: "BankMuamalatV3ROU",
    component: BankMuamalatV3ROU,
  },
  {
    name: "BankMuamalat V3 SQU",
    slug: "bank-muamalat-v3-squ",
    category: "Banks",
    componentName: "BankMuamalatV3SQU",
    component: BankMuamalatV3SQU,
  },
  {
    name: "BankMuamalat V4 ROU",
    slug: "bank-muamalat-v4-rou",
    category: "Banks",
    componentName: "BankMuamalatV4ROU",
    component: BankMuamalatV4ROU,
  },
  {
    name: "BankMuamalat V4 SQU",
    slug: "bank-muamalat-v4-squ",
    category: "Banks",
    componentName: "BankMuamalatV4SQU",
    component: BankMuamalatV4SQU,
  },
  {
    name: "BankOfChina SVG",
    slug: "bank-of-china-svg",
    category: "Banks",
    componentName: "BankOfChinaSVG",
    component: BankOfChinaSVG,
  },
  {
    name: "BankOfChina V1 BSQU",
    slug: "bank-of-china-v1-bsqu",
    category: "Banks",
    componentName: "BankOfChinaV1BSQU",
    component: BankOfChinaV1BSQU,
  },
  {
    name: "BankOfChina V1 LG",
    slug: "bank-of-china-v1-lg",
    category: "Banks",
    componentName: "BankOfChinaV1LG",
    component: BankOfChinaV1LG,
  },
  {
    name: "BankOfChina V1 ROU",
    slug: "bank-of-china-v1-rou",
    category: "Banks",
    componentName: "BankOfChinaV1ROU",
    component: BankOfChinaV1ROU,
  },
  {
    name: "BankOfChina V1 SQU",
    slug: "bank-of-china-v1-squ",
    category: "Banks",
    componentName: "BankOfChinaV1SQU",
    component: BankOfChinaV1SQU,
  },
  {
    name: "BankRakyat SVG",
    slug: "bank-rakyat-svg",
    category: "Banks",
    componentName: "BankRakyatSVG",
    component: BankRakyatSVG,
  },
  {
    name: "BankRakyat V1 BSQU",
    slug: "bank-rakyat-v1-bsqu",
    category: "Banks",
    componentName: "BankRakyatV1BSQU",
    component: BankRakyatV1BSQU,
  },
  {
    name: "BankRakyat V1 LG",
    slug: "bank-rakyat-v1-lg",
    category: "Banks",
    componentName: "BankRakyatV1LG",
    component: BankRakyatV1LG,
  },
  {
    name: "BankRakyat V1 ROU",
    slug: "bank-rakyat-v1-rou",
    category: "Banks",
    componentName: "BankRakyatV1ROU",
    component: BankRakyatV1ROU,
  },
  {
    name: "BankRakyat V1 SQU",
    slug: "bank-rakyat-v1-squ",
    category: "Banks",
    componentName: "BankRakyatV1SQU",
    component: BankRakyatV1SQU,
  },
  {
    name: "BankRakyat V2 BSQU",
    slug: "bank-rakyat-v2-bsqu",
    category: "Banks",
    componentName: "BankRakyatV2BSQU",
    component: BankRakyatV2BSQU,
  },
  {
    name: "BankRakyat V2 LG",
    slug: "bank-rakyat-v2-lg",
    category: "Banks",
    componentName: "BankRakyatV2LG",
    component: BankRakyatV2LG,
  },
  {
    name: "BankRakyat V2 ROU",
    slug: "bank-rakyat-v2-rou",
    category: "Banks",
    componentName: "BankRakyatV2ROU",
    component: BankRakyatV2ROU,
  },
  {
    name: "BankRakyat V2 SQU",
    slug: "bank-rakyat-v2-squ",
    category: "Banks",
    componentName: "BankRakyatV2SQU",
    component: BankRakyatV2SQU,
  },
  {
    name: "Binfinite SVG",
    slug: "binfinite-svg",
    category: "Wallet",
    componentName: "BinfiniteSVG",
    component: BinfiniteSVG,
  },
  {
    name: "Binfinite V1 ROU",
    slug: "binfinite-v1-rou",
    category: "Wallet",
    componentName: "BinfiniteV1ROU",
    component: BinfiniteV1ROU,
  },
  {
    name: "Binfinite V1 SQU",
    slug: "binfinite-v1-squ",
    category: "Wallet",
    componentName: "BinfiniteV1SQU",
    component: BinfiniteV1SQU,
  },
  {
    name: "Binfinite V2 ROU",
    slug: "binfinite-v2-rou",
    category: "Wallet",
    componentName: "BinfiniteV2ROU",
    component: BinfiniteV2ROU,
  },
  {
    name: "Binfinite V2 SQU",
    slug: "binfinite-v2-squ",
    category: "Wallet",
    componentName: "BinfiniteV2SQU",
    component: BinfiniteV2SQU,
  },
  {
    name: "Binfinite V3 ROU",
    slug: "binfinite-v3-rou",
    category: "Wallet",
    componentName: "BinfiniteV3ROU",
    component: BinfiniteV3ROU,
  },
  {
    name: "Binfinite V3 SQU",
    slug: "binfinite-v3-squ",
    category: "Wallet",
    componentName: "BinfiniteV3SQU",
    component: BinfiniteV3SQU,
  },
  {
    name: "BNPParibasBank SVG",
    slug: "bnpparibas-bank-svg",
    category: "Banks",
    componentName: "BNPParibasBankSVG",
    component: BNPParibasBankSVG,
  },
  {
    name: "BNPParibasBank V1 BSQU",
    slug: "bnpparibas-bank-v1-bsqu",
    category: "Banks",
    componentName: "BNPParibasBankV1BSQU",
    component: BNPParibasBankV1BSQU,
  },
  {
    name: "BNPParibasBank V1 LG",
    slug: "bnpparibas-bank-v1-lg",
    category: "Banks",
    componentName: "BNPParibasBankV1LG",
    component: BNPParibasBankV1LG,
  },
  {
    name: "BNPParibasBank V1 ROU",
    slug: "bnpparibas-bank-v1-rou",
    category: "Banks",
    componentName: "BNPParibasBankV1ROU",
    component: BNPParibasBankV1ROU,
  },
  {
    name: "BNPParibasBank V1 SQU",
    slug: "bnpparibas-bank-v1-squ",
    category: "Banks",
    componentName: "BNPParibasBankV1SQU",
    component: BNPParibasBankV1SQU,
  },
  {
    name: "BNPParibasBank V2 BSQU",
    slug: "bnpparibas-bank-v2-bsqu",
    category: "Banks",
    componentName: "BNPParibasBankV2BSQU",
    component: BNPParibasBankV2BSQU,
  },
  {
    name: "BNPParibasBank V2 LG",
    slug: "bnpparibas-bank-v2-lg",
    category: "Banks",
    componentName: "BNPParibasBankV2LG",
    component: BNPParibasBankV2LG,
  },
  {
    name: "BNPParibasBank V2 ROU",
    slug: "bnpparibas-bank-v2-rou",
    category: "Banks",
    componentName: "BNPParibasBankV2ROU",
    component: BNPParibasBankV2ROU,
  },
  {
    name: "BNPParibasBank V2 SQU",
    slug: "bnpparibas-bank-v2-squ",
    category: "Banks",
    componentName: "BNPParibasBankV2SQU",
    component: BNPParibasBankV2SQU,
  },
  {
    name: "Boost SVG",
    slug: "boost-svg",
    category: "Wallet",
    componentName: "BoostSVG",
    component: BoostSVG,
  },
  {
    name: "Boost V1 ROU",
    slug: "boost-v1-rou",
    category: "Wallet",
    componentName: "BoostV1ROU",
    component: BoostV1ROU,
  },
  {
    name: "Boost V1 SQU",
    slug: "boost-v1-squ",
    category: "Wallet",
    componentName: "BoostV1SQU",
    component: BoostV1SQU,
  },
  {
    name: "Boost V2 ROU",
    slug: "boost-v2-rou",
    category: "Wallet",
    componentName: "BoostV2ROU",
    component: BoostV2ROU,
  },
  {
    name: "Boost V2 SQU",
    slug: "boost-v2-squ",
    category: "Wallet",
    componentName: "BoostV2SQU",
    component: BoostV2SQU,
  },
  {
    name: "Boost V3 ROU",
    slug: "boost-v3-rou",
    category: "Wallet",
    componentName: "BoostV3ROU",
    component: BoostV3ROU,
  },
  {
    name: "Boost V3 SQU",
    slug: "boost-v3-squ",
    category: "Wallet",
    componentName: "BoostV3SQU",
    component: BoostV3SQU,
  },
  {
    name: "BoostBank SVG",
    slug: "boost-bank-svg",
    category: "Banks",
    componentName: "BoostBankSVG",
    component: BoostBankSVG,
  },
  {
    name: "BoostBank V1 BSQU",
    slug: "boost-bank-v1-bsqu",
    category: "Banks",
    componentName: "BoostBankV1BSQU",
    component: BoostBankV1BSQU,
  },
  {
    name: "BoostBank V1 LG",
    slug: "boost-bank-v1-lg",
    category: "Banks",
    componentName: "BoostBankV1LG",
    component: BoostBankV1LG,
  },
  {
    name: "BoostBank V1 ROU",
    slug: "boost-bank-v1-rou",
    category: "Banks",
    componentName: "BoostBankV1ROU",
    component: BoostBankV1ROU,
  },
  {
    name: "BoostBank V1 SQU",
    slug: "boost-bank-v1-squ",
    category: "Banks",
    componentName: "BoostBankV1SQU",
    component: BoostBankV1SQU,
  },
  {
    name: "BSN SVG",
    slug: "bsn-svg",
    category: "Banks",
    componentName: "BSNSVG",
    component: BSNSVG,
  },
  {
    name: "BSN V1 BSQU",
    slug: "bsn-v1-bsqu",
    category: "Banks",
    componentName: "BSNV1BSQU",
    component: BSNV1BSQU,
  },
  {
    name: "BSN V1 LG",
    slug: "bsn-v1-lg",
    category: "Banks",
    componentName: "BSNV1LG",
    component: BSNV1LG,
  },
  {
    name: "BSN V1 ROU",
    slug: "bsn-v1-rou",
    category: "Banks",
    componentName: "BSNV1ROU",
    component: BSNV1ROU,
  },
  {
    name: "BSN V1 SQU",
    slug: "bsn-v1-squ",
    category: "Banks",
    componentName: "BSNV1SQU",
    component: BSNV1SQU,
  },
  {
    name: "Card SVG",
    slug: "card-svg",
    category: "Other",
    componentName: "CardSVG",
    component: CardSVG,
  },
  {
    name: "Card V1 ROU",
    slug: "card-v1-rou",
    category: "Other",
    componentName: "CardV1ROU",
    component: CardV1ROU,
  },
  {
    name: "Card V1 SQU",
    slug: "card-v1-squ",
    category: "Other",
    componentName: "CardV1SQU",
    component: CardV1SQU,
  },
  {
    name: "Cimb SVG",
    slug: "cimb-svg",
    category: "Banks",
    componentName: "CimbSVG",
    component: CimbSVG,
  },
  {
    name: "Cimb V1 BSQU",
    slug: "cimb-v1-bsqu",
    category: "Banks",
    componentName: "CimbV1BSQU",
    component: CimbV1BSQU,
  },
  {
    name: "Cimb V1 LG",
    slug: "cimb-v1-lg",
    category: "Banks",
    componentName: "CimbV1LG",
    component: CimbV1LG,
  },
  {
    name: "Cimb V1 ROU",
    slug: "cimb-v1-rou",
    category: "Banks",
    componentName: "CimbV1ROU",
    component: CimbV1ROU,
  },
  {
    name: "Cimb V1 SQU",
    slug: "cimb-v1-squ",
    category: "Banks",
    componentName: "CimbV1SQU",
    component: CimbV1SQU,
  },
  {
    name: "Cimb V2 BSQU",
    slug: "cimb-v2-bsqu",
    category: "Banks",
    componentName: "CimbV2BSQU",
    component: CimbV2BSQU,
  },
  {
    name: "Cimb V2 LG",
    slug: "cimb-v2-lg",
    category: "Banks",
    componentName: "CimbV2LG",
    component: CimbV2LG,
  },
  {
    name: "Cimb V2 ROU",
    slug: "cimb-v2-rou",
    category: "Banks",
    componentName: "CimbV2ROU",
    component: CimbV2ROU,
  },
  {
    name: "Cimb V2 SQU",
    slug: "cimb-v2-squ",
    category: "Banks",
    componentName: "CimbV2SQU",
    component: CimbV2SQU,
  },
  {
    name: "Cimb V3 BSQU",
    slug: "cimb-v3-bsqu",
    category: "Banks",
    componentName: "CimbV3BSQU",
    component: CimbV3BSQU,
  },
  {
    name: "Cimb V3 LG",
    slug: "cimb-v3-lg",
    category: "Banks",
    componentName: "CimbV3LG",
    component: CimbV3LG,
  },
  {
    name: "Cimb V3 ROU",
    slug: "cimb-v3-rou",
    category: "Banks",
    componentName: "CimbV3ROU",
    component: CimbV3ROU,
  },
  {
    name: "Cimb V3 SQU",
    slug: "cimb-v3-squ",
    category: "Banks",
    componentName: "CimbV3SQU",
    component: CimbV3SQU,
  },
  {
    name: "Cimb V4 BSQU",
    slug: "cimb-v4-bsqu",
    category: "Banks",
    componentName: "CimbV4BSQU",
    component: CimbV4BSQU,
  },
  {
    name: "Cimb V4 LG",
    slug: "cimb-v4-lg",
    category: "Banks",
    componentName: "CimbV4LG",
    component: CimbV4LG,
  },
  {
    name: "Cimb V5 LG",
    slug: "cimb-v5-lg",
    category: "Banks",
    componentName: "CimbV5LG",
    component: CimbV5LG,
  },
  {
    name: "CitiBank SVG",
    slug: "citi-bank-svg",
    category: "Banks",
    componentName: "CitiBankSVG",
    component: CitiBankSVG,
  },
  {
    name: "CitiBank V1 BSQU",
    slug: "citi-bank-v1-bsqu",
    category: "Banks",
    componentName: "CitiBankV1BSQU",
    component: CitiBankV1BSQU,
  },
  {
    name: "CitiBank V1 LG",
    slug: "citi-bank-v1-lg",
    category: "Banks",
    componentName: "CitiBankV1LG",
    component: CitiBankV1LG,
  },
  {
    name: "CitiBank V1 ROU",
    slug: "citi-bank-v1-rou",
    category: "Banks",
    componentName: "CitiBankV1ROU",
    component: CitiBankV1ROU,
  },
  {
    name: "CitiBank V1 SQU",
    slug: "citi-bank-v1-squ",
    category: "Banks",
    componentName: "CitiBankV1SQU",
    component: CitiBankV1SQU,
  },
  {
    name: "CitiBank V2 BSQU",
    slug: "citi-bank-v2-bsqu",
    category: "Banks",
    componentName: "CitiBankV2BSQU",
    component: CitiBankV2BSQU,
  },
  {
    name: "CitiBank V2 LG",
    slug: "citi-bank-v2-lg",
    category: "Banks",
    componentName: "CitiBankV2LG",
    component: CitiBankV2LG,
  },
  {
    name: "CitiBank V2 ROU",
    slug: "citi-bank-v2-rou",
    category: "Banks",
    componentName: "CitiBankV2ROU",
    component: CitiBankV2ROU,
  },
  {
    name: "CitiBank V2 SQU",
    slug: "citi-bank-v2-squ",
    category: "Banks",
    componentName: "CitiBankV2SQU",
    component: CitiBankV2SQU,
  },
  {
    name: "DeutscheBank SVG",
    slug: "deutsche-bank-svg",
    category: "Banks",
    componentName: "DeutscheBankSVG",
    component: DeutscheBankSVG,
  },
  {
    name: "DeutscheBank V1 BSQU",
    slug: "deutsche-bank-v1-bsqu",
    category: "Banks",
    componentName: "DeutscheBankV1BSQU",
    component: DeutscheBankV1BSQU,
  },
  {
    name: "DeutscheBank V1 LG",
    slug: "deutsche-bank-v1-lg",
    category: "Banks",
    componentName: "DeutscheBankV1LG",
    component: DeutscheBankV1LG,
  },
  {
    name: "DeutscheBank V1 ROU",
    slug: "deutsche-bank-v1-rou",
    category: "Banks",
    componentName: "DeutscheBankV1ROU",
    component: DeutscheBankV1ROU,
  },
  {
    name: "DeutscheBank V1 SQU",
    slug: "deutsche-bank-v1-squ",
    category: "Banks",
    componentName: "DeutscheBankV1SQU",
    component: DeutscheBankV1SQU,
  },
  {
    name: "DeutscheBank V2 BSQU",
    slug: "deutsche-bank-v2-bsqu",
    category: "Banks",
    componentName: "DeutscheBankV2BSQU",
    component: DeutscheBankV2BSQU,
  },
  {
    name: "DeutscheBank V2 LG",
    slug: "deutsche-bank-v2-lg",
    category: "Banks",
    componentName: "DeutscheBankV2LG",
    component: DeutscheBankV2LG,
  },
  {
    name: "DeutscheBank V2 ROU",
    slug: "deutsche-bank-v2-rou",
    category: "Banks",
    componentName: "DeutscheBankV2ROU",
    component: DeutscheBankV2ROU,
  },
  {
    name: "DeutscheBank V2 SQU",
    slug: "deutsche-bank-v2-squ",
    category: "Banks",
    componentName: "DeutscheBankV2SQU",
    component: DeutscheBankV2SQU,
  },
  {
    name: "DuitNow SVG",
    slug: "duit-now-svg",
    category: "Other",
    componentName: "DuitNowSVG",
    component: DuitNowSVG,
  },
  {
    name: "DuitNow V1 ROU",
    slug: "duit-now-v1-rou",
    category: "Other",
    componentName: "DuitNowV1ROU",
    component: DuitNowV1ROU,
  },
  {
    name: "DuitNow V1 SQU",
    slug: "duit-now-v1-squ",
    category: "Other",
    componentName: "DuitNowV1SQU",
    component: DuitNowV1SQU,
  },
  {
    name: "DuitNow V2 ROU",
    slug: "duit-now-v2-rou",
    category: "Other",
    componentName: "DuitNowV2ROU",
    component: DuitNowV2ROU,
  },
  {
    name: "DuitNow V2 SQU",
    slug: "duit-now-v2-squ",
    category: "Other",
    componentName: "DuitNowV2SQU",
    component: DuitNowV2SQU,
  },
  {
    name: "DuitNow V3 ROU",
    slug: "duit-now-v3-rou",
    category: "Other",
    componentName: "DuitNowV3ROU",
    component: DuitNowV3ROU,
  },
  {
    name: "DuitNow V3 SQU",
    slug: "duit-now-v3-squ",
    category: "Other",
    componentName: "DuitNowV3SQU",
    component: DuitNowV3SQU,
  },
  {
    name: "DuitNow V4 ROU",
    slug: "duit-now-v4-rou",
    category: "Other",
    componentName: "DuitNowV4ROU",
    component: DuitNowV4ROU,
  },
  {
    name: "DuitNow V4 SQU",
    slug: "duit-now-v4-squ",
    category: "Other",
    componentName: "DuitNowV4SQU",
    component: DuitNowV4SQU,
  },
  {
    name: "FavePay SVG",
    slug: "fave-pay-svg",
    category: "Wallet",
    componentName: "FavePaySVG",
    component: FavePaySVG,
  },
  {
    name: "FavePay V1 ROU",
    slug: "fave-pay-v1-rou",
    category: "Wallet",
    componentName: "FavePayV1ROU",
    component: FavePayV1ROU,
  },
  {
    name: "FavePay V1 SQU",
    slug: "fave-pay-v1-squ",
    category: "Wallet",
    componentName: "FavePayV1SQU",
    component: FavePayV1SQU,
  },
  {
    name: "FavePay V2 ROU",
    slug: "fave-pay-v2-rou",
    category: "Wallet",
    componentName: "FavePayV2ROU",
    component: FavePayV2ROU,
  },
  {
    name: "FavePay V2 SQU",
    slug: "fave-pay-v2-squ",
    category: "Wallet",
    componentName: "FavePayV2SQU",
    component: FavePayV2SQU,
  },
  {
    name: "FPX SVG",
    slug: "fpx-svg",
    category: "Other",
    componentName: "FPXSVG",
    component: FPXSVG,
  },
  {
    name: "FPX V1 ROU",
    slug: "fpx-v1-rou",
    category: "Other",
    componentName: "FPXV1ROU",
    component: FPXV1ROU,
  },
  {
    name: "FPX V1 SQU",
    slug: "fpx-v1-squ",
    category: "Other",
    componentName: "FPXV1SQU",
    component: FPXV1SQU,
  },
  {
    name: "FPX V2 ROU",
    slug: "fpx-v2-rou",
    category: "Other",
    componentName: "FPXV2ROU",
    component: FPXV2ROU,
  },
  {
    name: "FPX V2 SQU",
    slug: "fpx-v2-squ",
    category: "Other",
    componentName: "FPXV2SQU",
    component: FPXV2SQU,
  },
  {
    name: "FPX V3 ROU",
    slug: "fpx-v3-rou",
    category: "Other",
    componentName: "FPXV3ROU",
    component: FPXV3ROU,
  },
  {
    name: "FPX V3 SQU",
    slug: "fpx-v3-squ",
    category: "Other",
    componentName: "FPXV3SQU",
    component: FPXV3SQU,
  },
  {
    name: "Gobiz SVG",
    slug: "gobiz-svg",
    category: "Card",
    componentName: "GobizSVG",
    component: GobizSVG,
  },
  {
    name: "Gobiz V1 ROU",
    slug: "gobiz-v1-rou",
    category: "Card",
    componentName: "GobizV1ROU",
    component: GobizV1ROU,
  },
  {
    name: "Gobiz V1 SQU",
    slug: "gobiz-v1-squ",
    category: "Card",
    componentName: "GobizV1SQU",
    component: GobizV1SQU,
  },
  {
    name: "Gobiz V2 ROU",
    slug: "gobiz-v2-rou",
    category: "Card",
    componentName: "GobizV2ROU",
    component: GobizV2ROU,
  },
  {
    name: "Gobiz V2 SQU",
    slug: "gobiz-v2-squ",
    category: "Card",
    componentName: "GobizV2SQU",
    component: GobizV2SQU,
  },
  {
    name: "GooglePay SVG",
    slug: "google-pay-svg",
    category: "Mobile",
    componentName: "GooglePaySVG",
    component: GooglePaySVG,
  },
  {
    name: "GooglePay V1 ROU",
    slug: "google-pay-v1-rou",
    category: "Mobile",
    componentName: "GooglePayV1ROU",
    component: GooglePayV1ROU,
  },
  {
    name: "GooglePay V1 SQU",
    slug: "google-pay-v1-squ",
    category: "Mobile",
    componentName: "GooglePayV1SQU",
    component: GooglePayV1SQU,
  },
  {
    name: "GooglePay V1 TRSP",
    slug: "google-pay-v1-trsp",
    category: "Mobile",
    componentName: "GooglePayV1TRSP",
    component: GooglePayV1TRSP,
  },
  {
    name: "GooglePay V2 ROU",
    slug: "google-pay-v2-rou",
    category: "Mobile",
    componentName: "GooglePayV2ROU",
    component: GooglePayV2ROU,
  },
  {
    name: "GooglePay V2 SQU",
    slug: "google-pay-v2-squ",
    category: "Mobile",
    componentName: "GooglePayV2SQU",
    component: GooglePayV2SQU,
  },
  {
    name: "GooglePay V2 TRSP",
    slug: "google-pay-v2-trsp",
    category: "Mobile",
    componentName: "GooglePayV2TRSP",
    component: GooglePayV2TRSP,
  },
  {
    name: "GooglePay V3 ROU",
    slug: "google-pay-v3-rou",
    category: "Mobile",
    componentName: "GooglePayV3ROU",
    component: GooglePayV3ROU,
  },
  {
    name: "GooglePay V3 SQU",
    slug: "google-pay-v3-squ",
    category: "Mobile",
    componentName: "GooglePayV3SQU",
    component: GooglePayV3SQU,
  },
  {
    name: "GooglePay V3 TRSP",
    slug: "google-pay-v3-trsp",
    category: "Mobile",
    componentName: "GooglePayV3TRSP",
    component: GooglePayV3TRSP,
  },
  {
    name: "GoPayz SVG",
    slug: "go-payz-svg",
    category: "Wallet",
    componentName: "GoPayzSVG",
    component: GoPayzSVG,
  },
  {
    name: "GoPayz V1 ROU",
    slug: "go-payz-v1-rou",
    category: "Wallet",
    componentName: "GoPayzV1ROU",
    component: GoPayzV1ROU,
  },
  {
    name: "GoPayz V1 SQU",
    slug: "go-payz-v1-squ",
    category: "Wallet",
    componentName: "GoPayzV1SQU",
    component: GoPayzV1SQU,
  },
  {
    name: "GoPayz V2 ROU",
    slug: "go-payz-v2-rou",
    category: "Wallet",
    componentName: "GoPayzV2ROU",
    component: GoPayzV2ROU,
  },
  {
    name: "GoPayz V2 SQU",
    slug: "go-payz-v2-squ",
    category: "Wallet",
    componentName: "GoPayzV2SQU",
    component: GoPayzV2SQU,
  },
  {
    name: "GrabPay SVG",
    slug: "grab-pay-svg",
    category: "Wallet",
    componentName: "GrabPaySVG",
    component: GrabPaySVG,
  },
  {
    name: "GrabPay V1 ROU",
    slug: "grab-pay-v1-rou",
    category: "Wallet",
    componentName: "GrabPayV1ROU",
    component: GrabPayV1ROU,
  },
  {
    name: "GrabPay V1 SQU",
    slug: "grab-pay-v1-squ",
    category: "Wallet",
    componentName: "GrabPayV1SQU",
    component: GrabPayV1SQU,
  },
  {
    name: "GrabPay V2 ROU",
    slug: "grab-pay-v2-rou",
    category: "Wallet",
    componentName: "GrabPayV2ROU",
    component: GrabPayV2ROU,
  },
  {
    name: "GrabPay V2 SQU",
    slug: "grab-pay-v2-squ",
    category: "Wallet",
    componentName: "GrabPayV2SQU",
    component: GrabPayV2SQU,
  },
  {
    name: "GrabPay V3 ROU",
    slug: "grab-pay-v3-rou",
    category: "Wallet",
    componentName: "GrabPayV3ROU",
    component: GrabPayV3ROU,
  },
  {
    name: "GrabPay V3 SQU",
    slug: "grab-pay-v3-squ",
    category: "Wallet",
    componentName: "GrabPayV3SQU",
    component: GrabPayV3SQU,
  },
  {
    name: "GrabPay V4 ROU",
    slug: "grab-pay-v4-rou",
    category: "Wallet",
    componentName: "GrabPayV4ROU",
    component: GrabPayV4ROU,
  },
  {
    name: "GrabPay V4 SQU",
    slug: "grab-pay-v4-squ",
    category: "Wallet",
    componentName: "GrabPayV4SQU",
    component: GrabPayV4SQU,
  },
  {
    name: "GrabPayLater SVG",
    slug: "grab-pay-later-svg",
    category: "BNPL",
    componentName: "GrabPayLaterSVG",
    component: GrabPayLaterSVG,
  },
  {
    name: "GrabPayLater V1 LG",
    slug: "grab-pay-later-v1-lg",
    category: "BNPL",
    componentName: "GrabPayLaterV1LG",
    component: GrabPayLaterV1LG,
  },
  {
    name: "GrabPayLater V2 LG",
    slug: "grab-pay-later-v2-lg",
    category: "BNPL",
    componentName: "GrabPayLaterV2LG",
    component: GrabPayLaterV2LG,
  },
  {
    name: "GXBank SVG",
    slug: "gxbank-svg",
    category: "Banks",
    componentName: "GXBankSVG",
    component: GXBankSVG,
  },
  {
    name: "GXBank V1 BSQU",
    slug: "gxbank-v1-bsqu",
    category: "Banks",
    componentName: "GXBankV1BSQU",
    component: GXBankV1BSQU,
  },
  {
    name: "GXBank V1 LG",
    slug: "gxbank-v1-lg",
    category: "Banks",
    componentName: "GXBankV1LG",
    component: GXBankV1LG,
  },
  {
    name: "GXBank V1 ROU",
    slug: "gxbank-v1-rou",
    category: "Banks",
    componentName: "GXBankV1ROU",
    component: GXBankV1ROU,
  },
  {
    name: "GXBank V1 SQU",
    slug: "gxbank-v1-squ",
    category: "Banks",
    componentName: "GXBankV1SQU",
    component: GXBankV1SQU,
  },
  {
    name: "GXBank V2 BSQU",
    slug: "gxbank-v2-bsqu",
    category: "Banks",
    componentName: "GXBankV2BSQU",
    component: GXBankV2BSQU,
  },
  {
    name: "GXBank V2 LG",
    slug: "gxbank-v2-lg",
    category: "Banks",
    componentName: "GXBankV2LG",
    component: GXBankV2LG,
  },
  {
    name: "GXBank V2 ROU",
    slug: "gxbank-v2-rou",
    category: "Banks",
    componentName: "GXBankV2ROU",
    component: GXBankV2ROU,
  },
  {
    name: "GXBank V2 SQU",
    slug: "gxbank-v2-squ",
    category: "Banks",
    componentName: "GXBankV2SQU",
    component: GXBankV2SQU,
  },
  {
    name: "GXBank V3 BSQU",
    slug: "gxbank-v3-bsqu",
    category: "Banks",
    componentName: "GXBankV3BSQU",
    component: GXBankV3BSQU,
  },
  {
    name: "GXBank V3 LG",
    slug: "gxbank-v3-lg",
    category: "Banks",
    componentName: "GXBankV3LG",
    component: GXBankV3LG,
  },
  {
    name: "GXBank V3 ROU",
    slug: "gxbank-v3-rou",
    category: "Banks",
    componentName: "GXBankV3ROU",
    component: GXBankV3ROU,
  },
  {
    name: "GXBank V3 SQU",
    slug: "gxbank-v3-squ",
    category: "Banks",
    componentName: "GXBankV3SQU",
    component: GXBankV3SQU,
  },
  {
    name: "GXBank V4 BSQU",
    slug: "gxbank-v4-bsqu",
    category: "Banks",
    componentName: "GXBankV4BSQU",
    component: GXBankV4BSQU,
  },
  {
    name: "GXBank V4 LG",
    slug: "gxbank-v4-lg",
    category: "Banks",
    componentName: "GXBankV4LG",
    component: GXBankV4LG,
  },
  {
    name: "GXBank V4 ROU",
    slug: "gxbank-v4-rou",
    category: "Banks",
    componentName: "GXBankV4ROU",
    component: GXBankV4ROU,
  },
  {
    name: "GXBank V4 SQU",
    slug: "gxbank-v4-squ",
    category: "Banks",
    componentName: "GXBankV4SQU",
    component: GXBankV4SQU,
  },
  {
    name: "GXBank V5 BSQU",
    slug: "gxbank-v5-bsqu",
    category: "Banks",
    componentName: "GXBankV5BSQU",
    component: GXBankV5BSQU,
  },
  {
    name: "GXBank V5 LG",
    slug: "gxbank-v5-lg",
    category: "Banks",
    componentName: "GXBankV5LG",
    component: GXBankV5LG,
  },
  {
    name: "GXBank V5 ROU",
    slug: "gxbank-v5-rou",
    category: "Banks",
    componentName: "GXBankV5ROU",
    component: GXBankV5ROU,
  },
  {
    name: "GXBank V5 SQU",
    slug: "gxbank-v5-squ",
    category: "Banks",
    componentName: "GXBankV5SQU",
    component: GXBankV5SQU,
  },
  {
    name: "HongLeongBank SVG",
    slug: "hong-leong-bank-svg",
    category: "Banks",
    componentName: "HongLeongBankSVG",
    component: HongLeongBankSVG,
  },
  {
    name: "HongLeongBank V1 BSQU",
    slug: "hong-leong-bank-v1-bsqu",
    category: "Banks",
    componentName: "HongLeongBankV1BSQU",
    component: HongLeongBankV1BSQU,
  },
  {
    name: "HongLeongBank V1 LG",
    slug: "hong-leong-bank-v1-lg",
    category: "Banks",
    componentName: "HongLeongBankV1LG",
    component: HongLeongBankV1LG,
  },
  {
    name: "HongLeongBank V1 ROU",
    slug: "hong-leong-bank-v1-rou",
    category: "Banks",
    componentName: "HongLeongBankV1ROU",
    component: HongLeongBankV1ROU,
  },
  {
    name: "HongLeongBank V1 SQU",
    slug: "hong-leong-bank-v1-squ",
    category: "Banks",
    componentName: "HongLeongBankV1SQU",
    component: HongLeongBankV1SQU,
  },
  {
    name: "HongLeongBank V2 BSQU",
    slug: "hong-leong-bank-v2-bsqu",
    category: "Banks",
    componentName: "HongLeongBankV2BSQU",
    component: HongLeongBankV2BSQU,
  },
  {
    name: "HongLeongBank V2 LG",
    slug: "hong-leong-bank-v2-lg",
    category: "Banks",
    componentName: "HongLeongBankV2LG",
    component: HongLeongBankV2LG,
  },
  {
    name: "HSBC SVG",
    slug: "hsbc-svg",
    category: "Banks",
    componentName: "HSBCSVG",
    component: HSBCSVG,
  },
  {
    name: "HSBC V1 BSQU",
    slug: "hsbc-v1-bsqu",
    category: "Banks",
    componentName: "HSBCV1BSQU",
    component: HSBCV1BSQU,
  },
  {
    name: "HSBC V1 LG",
    slug: "hsbc-v1-lg",
    category: "Banks",
    componentName: "HSBCV1LG",
    component: HSBCV1LG,
  },
  {
    name: "HSBC V1 ROU",
    slug: "hsbc-v1-rou",
    category: "Banks",
    componentName: "HSBCV1ROU",
    component: HSBCV1ROU,
  },
  {
    name: "HSBC V1 SQU",
    slug: "hsbc-v1-squ",
    category: "Banks",
    componentName: "HSBCV1SQU",
    component: HSBCV1SQU,
  },
  {
    name: "IOUPay SVG",
    slug: "ioupay-svg",
    category: "BNPL",
    componentName: "IOUPaySVG",
    component: IOUPaySVG,
  },
  {
    name: "IOUPay V1 ROU",
    slug: "ioupay-v1-rou",
    category: "BNPL",
    componentName: "IOUPayV1ROU",
    component: IOUPayV1ROU,
  },
  {
    name: "IOUPay V1 SQU",
    slug: "ioupay-v1-squ",
    category: "BNPL",
    componentName: "IOUPayV1SQU",
    component: IOUPayV1SQU,
  },
  {
    name: "IOUPay V2 ROU",
    slug: "ioupay-v2-rou",
    category: "BNPL",
    componentName: "IOUPayV2ROU",
    component: IOUPayV2ROU,
  },
  {
    name: "IOUPay V2 SQU",
    slug: "ioupay-v2-squ",
    category: "BNPL",
    componentName: "IOUPayV2SQU",
    component: IOUPayV2SQU,
  },
  {
    name: "KuwaitFinanceHouse SVG",
    slug: "kuwait-finance-house-svg",
    category: "Banks",
    componentName: "KuwaitFinanceHouseSVG",
    component: KuwaitFinanceHouseSVG,
  },
  {
    name: "KuwaitFinanceHouse V1 BSQU",
    slug: "kuwait-finance-house-v1-bsqu",
    category: "Banks",
    componentName: "KuwaitFinanceHouseV1BSQU",
    component: KuwaitFinanceHouseV1BSQU,
  },
  {
    name: "KuwaitFinanceHouse V1 LG",
    slug: "kuwait-finance-house-v1-lg",
    category: "Banks",
    componentName: "KuwaitFinanceHouseV1LG",
    component: KuwaitFinanceHouseV1LG,
  },
  {
    name: "KuwaitFinanceHouse V1 ROU",
    slug: "kuwait-finance-house-v1-rou",
    category: "Banks",
    componentName: "KuwaitFinanceHouseV1ROU",
    component: KuwaitFinanceHouseV1ROU,
  },
  {
    name: "KuwaitFinanceHouse V1 SQU",
    slug: "kuwait-finance-house-v1-squ",
    category: "Banks",
    componentName: "KuwaitFinanceHouseV1SQU",
    component: KuwaitFinanceHouseV1SQU,
  },
  {
    name: "KuwaitFinanceHouse V2 BSQU",
    slug: "kuwait-finance-house-v2-bsqu",
    category: "Banks",
    componentName: "KuwaitFinanceHouseV2BSQU",
    component: KuwaitFinanceHouseV2BSQU,
  },
  {
    name: "KuwaitFinanceHouse V2 LG",
    slug: "kuwait-finance-house-v2-lg",
    category: "Banks",
    componentName: "KuwaitFinanceHouseV2LG",
    component: KuwaitFinanceHouseV2LG,
  },
  {
    name: "KuwaitFinanceHouse V2 ROU",
    slug: "kuwait-finance-house-v2-rou",
    category: "Banks",
    componentName: "KuwaitFinanceHouseV2ROU",
    component: KuwaitFinanceHouseV2ROU,
  },
  {
    name: "KuwaitFinanceHouse V2 SQU",
    slug: "kuwait-finance-house-v2-squ",
    category: "Banks",
    componentName: "KuwaitFinanceHouseV2SQU",
    component: KuwaitFinanceHouseV2SQU,
  },
  {
    name: "Lazada SVG",
    slug: "lazada-svg",
    category: "Wallet",
    componentName: "LazadaSVG",
    component: LazadaSVG,
  },
  {
    name: "Lazada V1 ROU",
    slug: "lazada-v1-rou",
    category: "Wallet",
    componentName: "LazadaV1ROU",
    component: LazadaV1ROU,
  },
  {
    name: "Lazada V1 SQU",
    slug: "lazada-v1-squ",
    category: "Wallet",
    componentName: "LazadaV1SQU",
    component: LazadaV1SQU,
  },
  {
    name: "Lazada V2 ROU",
    slug: "lazada-v2-rou",
    category: "Wallet",
    componentName: "LazadaV2ROU",
    component: LazadaV2ROU,
  },
  {
    name: "Lazada V2 SQU",
    slug: "lazada-v2-squ",
    category: "Wallet",
    componentName: "LazadaV2SQU",
    component: LazadaV2SQU,
  },
  {
    name: "MAE SVG",
    slug: "mae-svg",
    category: "Wallet",
    componentName: "MAESVG",
    component: MAESVG,
  },
  {
    name: "MAE V1 ROU",
    slug: "mae-v1-rou",
    category: "Wallet",
    componentName: "MAEV1ROU",
    component: MAEV1ROU,
  },
  {
    name: "MAE V1 SQU",
    slug: "mae-v1-squ",
    category: "Wallet",
    componentName: "MAEV1SQU",
    component: MAEV1SQU,
  },
  {
    name: "MASTER SVG",
    slug: "master-svg",
    category: "Card",
    componentName: "MASTERSVG",
    component: MASTERSVG,
  },
  {
    name: "MASTER V1 ROU",
    slug: "master-v1-rou",
    category: "Card",
    componentName: "MASTERV1ROU",
    component: MASTERV1ROU,
  },
  {
    name: "MASTER V1 SQU",
    slug: "master-v1-squ",
    category: "Card",
    componentName: "MASTERV1SQU",
    component: MASTERV1SQU,
  },
  {
    name: "MASTER V1 TRSP",
    slug: "master-v1-trsp",
    category: "Card",
    componentName: "MASTERV1TRSP",
    component: MASTERV1TRSP,
  },
  {
    name: "MASTER V2 ROU",
    slug: "master-v2-rou",
    category: "Card",
    componentName: "MASTERV2ROU",
    component: MASTERV2ROU,
  },
  {
    name: "MASTER V2 SQU",
    slug: "master-v2-squ",
    category: "Card",
    componentName: "MASTERV2SQU",
    component: MASTERV2SQU,
  },
  {
    name: "MASTER V3 ROU",
    slug: "master-v3-rou",
    category: "Card",
    componentName: "MASTERV3ROU",
    component: MASTERV3ROU,
  },
  {
    name: "MASTER V3 SQU",
    slug: "master-v3-squ",
    category: "Card",
    componentName: "MASTERV3SQU",
    component: MASTERV3SQU,
  },
  {
    name: "MASTER V4 ROU",
    slug: "master-v4-rou",
    category: "Card",
    componentName: "MASTERV4ROU",
    component: MASTERV4ROU,
  },
  {
    name: "MASTER V4 SQU",
    slug: "master-v4-squ",
    category: "Card",
    componentName: "MASTERV4SQU",
    component: MASTERV4SQU,
  },

  {
    name: "MayBank V1 BSQU",
    slug: "may-bank-v1-bsqu",
    category: "Banks",
    componentName: "MayBankV1BSQU",
    component: MayBankV1BSQU,
  },
  {
    name: "MayBank V1 LG",
    slug: "may-bank-v1-lg",
    category: "Banks",
    componentName: "MayBankV1LG",
    component: MayBankV1LG,
  },
  {
    name: "MayBank V1 ROU",
    slug: "may-bank-v1-rou",
    category: "Banks",
    componentName: "MayBankV1ROU",
    component: MayBankV1ROU,
  },
  {
    name: "MayBank V1 SQU",
    slug: "may-bank-v1-squ",
    category: "Banks",
    componentName: "MayBankV1SQU",
    component: MayBankV1SQU,
  },
  {
    name: "MaybankQR V1 ROU",
    slug: "maybank-qr-v1-rou",
    category: "Other",
    componentName: "MaybankQRV1ROU",
    component: MaybankQRV1ROU,
  },
  {
    name: "MaybankQR V1 SQU",
    slug: "maybank-qr-v1-squ",
    category: "Other",
    componentName: "MaybankQRV1SQU",
    component: MaybankQRV1SQU,
  },
  {
    name: "MBSB SVG",
    slug: "mbsb-svg",
    category: "Banks",
    componentName: "MBSBSVG",
    component: MBSBSVG,
  },
  {
    name: "MBSB V1 BSQU",
    slug: "mbsb-v1-bsqu",
    category: "Banks",
    componentName: "MBSBV1BSQU",
    component: MBSBV1BSQU,
  },
  {
    name: "MBSB V1 LG",
    slug: "mbsb-v1-lg",
    category: "Banks",
    componentName: "MBSBV1LG",
    component: MBSBV1LG,
  },
  {
    name: "MBSB V1 ROU",
    slug: "mbsb-v1-rou",
    category: "Banks",
    componentName: "MBSBV1ROU",
    component: MBSBV1ROU,
  },
  {
    name: "MBSB V1 SQU",
    slug: "mbsb-v1-squ",
    category: "Banks",
    componentName: "MBSBV1SQU",
    component: MBSBV1SQU,
  },
  {
    name: "MCash SVG",
    slug: "mcash-svg",
    category: "Wallet",
    componentName: "MCashSVG",
    component: MCashSVG,
  },
  {
    name: "MCash V1 ROU",
    slug: "mcash-v1-rou",
    category: "Wallet",
    componentName: "MCashV1ROU",
    component: MCashV1ROU,
  },
  {
    name: "MCash V1 SQU",
    slug: "mcash-v1-squ",
    category: "Wallet",
    componentName: "MCashV1SQU",
    component: MCashV1SQU,
  },
  {
    name: "MCash V2 ROU",
    slug: "mcash-v2-rou",
    category: "Wallet",
    componentName: "MCashV2ROU",
    component: MCashV2ROU,
  },
  {
    name: "MCash V2 SQU",
    slug: "mcash-v2-squ",
    category: "Wallet",
    componentName: "MCashV2SQU",
    component: MCashV2SQU,
  },
  {
    name: "NetsPay SVG",
    slug: "nets-pay-svg",
    category: "Other",
    componentName: "NetsPaySVG",
    component: NetsPaySVG,
  },
  {
    name: "NetsPay V1 ROU",
    slug: "nets-pay-v1-rou",
    category: "Other",
    componentName: "NetsPayV1ROU",
    component: NetsPayV1ROU,
  },
  {
    name: "NetsPay V1 SQU",
    slug: "nets-pay-v1-squ",
    category: "Other",
    componentName: "NetsPayV1SQU",
    component: NetsPayV1SQU,
  },
  {
    name: "OCBC SVG",
    slug: "ocbc-svg",
    category: "Banks",
    componentName: "OCBCSVG",
    component: OCBCSVG,
  },
  {
    name: "OCBC V1 BSQU",
    slug: "ocbc-v1-bsqu",
    category: "Banks",
    componentName: "OCBCV1BSQU",
    component: OCBCV1BSQU,
  },
  {
    name: "OCBC V1 LG",
    slug: "ocbc-v1-lg",
    category: "Banks",
    componentName: "OCBCV1LG",
    component: OCBCV1LG,
  },
  {
    name: "OCBC V1 ROU",
    slug: "ocbc-v1-rou",
    category: "Banks",
    componentName: "OCBCV1ROU",
    component: OCBCV1ROU,
  },
  {
    name: "OCBC V1 SQU",
    slug: "ocbc-v1-squ",
    category: "Banks",
    componentName: "OCBCV1SQU",
    component: OCBCV1SQU,
  },
  {
    name: "OCBC V2 BSQU",
    slug: "ocbc-v2-bsqu",
    category: "Banks",
    componentName: "OCBCV2BSQU",
    component: OCBCV2BSQU,
  },
  {
    name: "OCBC V2 LG",
    slug: "ocbc-v2-lg",
    category: "Banks",
    componentName: "OCBCV2LG",
    component: OCBCV2LG,
  },
  {
    name: "OCBC V2 ROU",
    slug: "ocbc-v2-rou",
    category: "Banks",
    componentName: "OCBCV2ROU",
    component: OCBCV2ROU,
  },
  {
    name: "OCBC V2 SQU",
    slug: "ocbc-v2-squ",
    category: "Banks",
    componentName: "OCBCV2SQU",
    component: OCBCV2SQU,
  },
  {
    name: "Paydee SVG",
    slug: "paydee-svg",
    category: "Card",
    componentName: "PaydeeSVG",
    component: PaydeeSVG,
  },
  {
    name: "Paydee V1 ROU",
    slug: "paydee-v1-rou",
    category: "Card",
    componentName: "PaydeeV1ROU",
    component: PaydeeV1ROU,
  },
  {
    name: "Paydee V1 SQU",
    slug: "paydee-v1-squ",
    category: "Card",
    componentName: "PaydeeV1SQU",
    component: PaydeeV1SQU,
  },
  {
    name: "Paydee V2 ROU",
    slug: "paydee-v2-rou",
    category: "Card",
    componentName: "PaydeeV2ROU",
    component: PaydeeV2ROU,
  },
  {
    name: "Paydee V2 SQU",
    slug: "paydee-v2-squ",
    category: "Card",
    componentName: "PaydeeV2SQU",
    component: PaydeeV2SQU,
  },
  {
    name: "Presto SVG",
    slug: "presto-svg",
    category: "Wallet",
    componentName: "PrestoSVG",
    component: PrestoSVG,
  },
  {
    name: "Presto V1 ROU",
    slug: "presto-v1-rou",
    category: "Wallet",
    componentName: "PrestoV1ROU",
    component: PrestoV1ROU,
  },
  {
    name: "Presto V1 SQU",
    slug: "presto-v1-squ",
    category: "Wallet",
    componentName: "PrestoV1SQU",
    component: PrestoV1SQU,
  },
  {
    name: "Presto V2 ROU",
    slug: "presto-v2-rou",
    category: "Wallet",
    componentName: "PrestoV2ROU",
    component: PrestoV2ROU,
  },
  {
    name: "Presto V2 SQU",
    slug: "presto-v2-squ",
    category: "Wallet",
    componentName: "PrestoV2SQU",
    component: PrestoV2SQU,
  },
  {
    name: "Presto V3 ROU",
    slug: "presto-v3-rou",
    category: "Wallet",
    componentName: "PrestoV3ROU",
    component: PrestoV3ROU,
  },
  {
    name: "Presto V3 SQU",
    slug: "presto-v3-squ",
    category: "Wallet",
    componentName: "PrestoV3SQU",
    component: PrestoV3SQU,
  },
  {
    name: "Presto V4 ROU",
    slug: "presto-v4-rou",
    category: "Wallet",
    componentName: "PrestoV4ROU",
    component: PrestoV4ROU,
  },
  {
    name: "Presto V4 SQU",
    slug: "presto-v4-squ",
    category: "Wallet",
    componentName: "PrestoV4SQU",
    component: PrestoV4SQU,
  },
  {
    name: "Presto V5 ROU",
    slug: "presto-v5-rou",
    category: "Wallet",
    componentName: "PrestoV5ROU",
    component: PrestoV5ROU,
  },
  {
    name: "Presto V5 SQU",
    slug: "presto-v5-squ",
    category: "Wallet",
    componentName: "PrestoV5SQU",
    component: PrestoV5SQU,
  },
  {
    name: "PublicBank SVG",
    slug: "public-bank-svg",
    category: "Banks",
    componentName: "PublicBankSVG",
    component: PublicBankSVG,
  },
  {
    name: "PublicBank V1 BSQU",
    slug: "public-bank-v1-bsqu",
    category: "Banks",
    componentName: "PublicBankV1BSQU",
    component: PublicBankV1BSQU,
  },
  {
    name: "PublicBank V1 LG",
    slug: "public-bank-v1-lg",
    category: "Banks",
    componentName: "PublicBankV1LG",
    component: PublicBankV1LG,
  },
  {
    name: "PublicBank V1 ROU",
    slug: "public-bank-v1-rou",
    category: "Banks",
    componentName: "PublicBankV1ROU",
    component: PublicBankV1ROU,
  },
  {
    name: "PublicBank V1 SQU",
    slug: "public-bank-v1-squ",
    category: "Banks",
    componentName: "PublicBankV1SQU",
    component: PublicBankV1SQU,
  },
  {
    name: "RazerPay SVG",
    slug: "razer-pay-svg",
    category: "Wallet",
    componentName: "RazerPaySVG",
    component: RazerPaySVG,
  },
  {
    name: "RazerPay V1 ROU",
    slug: "razer-pay-v1-rou",
    category: "Wallet",
    componentName: "RazerPayV1ROU",
    component: RazerPayV1ROU,
  },
  {
    name: "RazerPay V1 SQU",
    slug: "razer-pay-v1-squ",
    category: "Wallet",
    componentName: "RazerPayV1SQU",
    component: RazerPayV1SQU,
  },
  {
    name: "RHB SVG",
    slug: "rhb-svg",
    category: "Banks",
    componentName: "RHBSVG",
    component: RHBSVG,
  },
  {
    name: "RHB V1 BSQU",
    slug: "rhb-v1-bsqu",
    category: "Banks",
    componentName: "RHBV1BSQU",
    component: RHBV1BSQU,
  },
  {
    name: "RHB V1 LG",
    slug: "rhb-v1-lg",
    category: "Banks",
    componentName: "RHBV1LG",
    component: RHBV1LG,
  },
  {
    name: "RHB V1 ROU",
    slug: "rhb-v1-rou",
    category: "Banks",
    componentName: "RHBV1ROU",
    component: RHBV1ROU,
  },
  {
    name: "RHB V1 SQU",
    slug: "rhb-v1-squ",
    category: "Banks",
    componentName: "RHBV1SQU",
    component: RHBV1SQU,
  },
  {
    name: "RHB V2 BSQU",
    slug: "rhb-v2-bsqu",
    category: "Banks",
    componentName: "RHBV2BSQU",
    component: RHBV2BSQU,
  },
  {
    name: "RHB V2 LG",
    slug: "rhb-v2-lg",
    category: "Banks",
    componentName: "RHBV2LG",
    component: RHBV2LG,
  },
  {
    name: "RHB V2 ROU",
    slug: "rhb-v2-rou",
    category: "Banks",
    componentName: "RHBV2ROU",
    component: RHBV2ROU,
  },
  {
    name: "RHB V2 SQU",
    slug: "rhb-v2-squ",
    category: "Banks",
    componentName: "RHBV2SQU",
    component: RHBV2SQU,
  },
  {
    name: "RytBank SVG",
    slug: "ryt-bank-svg",
    category: "Banks",
    componentName: "RytBankSVG",
    component: RytBankSVG,
  },
  {
    name: "RytBank V1 BSQU",
    slug: "ryt-bank-v1-bsqu",
    category: "Banks",
    componentName: "RytBankV1BSQU",
    component: RytBankV1BSQU,
  },
  {
    name: "RytBank V1 LG",
    slug: "ryt-bank-v1-lg",
    category: "Banks",
    componentName: "RytBankV1LG",
    component: RytBankV1LG,
  },
  {
    name: "RytBank V1 ROU",
    slug: "ryt-bank-v1-rou",
    category: "Banks",
    componentName: "RytBankV1ROU",
    component: RytBankV1ROU,
  },
  {
    name: "RytBank V1 SQU",
    slug: "ryt-bank-v1-squ",
    category: "Banks",
    componentName: "RytBankV1SQU",
    component: RytBankV1SQU,
  },
  {
    name: "RytBank V2 BSQU",
    slug: "ryt-bank-v2-bsqu",
    category: "Banks",
    componentName: "RytBankV2BSQU",
    component: RytBankV2BSQU,
  },
  {
    name: "RytBank V2 LG",
    slug: "ryt-bank-v2-lg",
    category: "Banks",
    componentName: "RytBankV2LG",
    component: RytBankV2LG,
  },
  {
    name: "RytBank V2 ROU",
    slug: "ryt-bank-v2-rou",
    category: "Banks",
    componentName: "RytBankV2ROU",
    component: RytBankV2ROU,
  },
  {
    name: "RytBank V2 SQU",
    slug: "ryt-bank-v2-squ",
    category: "Banks",
    componentName: "RytBankV2SQU",
    component: RytBankV2SQU,
  },
  {
    name: "SamsungPay SVG",
    slug: "samsung-pay-svg",
    category: "Mobile",
    componentName: "SamsungPaySVG",
    component: SamsungPaySVG,
  },
  {
    name: "SamsungPay V1 ROU",
    slug: "samsung-pay-v1-rou",
    category: "Mobile",
    componentName: "SamsungPayV1ROU",
    component: SamsungPayV1ROU,
  },
  {
    name: "SamsungPay V1 SQU",
    slug: "samsung-pay-v1-squ",
    category: "Mobile",
    componentName: "SamsungPayV1SQU",
    component: SamsungPayV1SQU,
  },
  {
    name: "SamsungPay V2 ROU",
    slug: "samsung-pay-v2-rou",
    category: "Mobile",
    componentName: "SamsungPayV2ROU",
    component: SamsungPayV2ROU,
  },
  {
    name: "SamsungPay V2 SQU",
    slug: "samsung-pay-v2-squ",
    category: "Mobile",
    componentName: "SamsungPayV2SQU",
    component: SamsungPayV2SQU,
  },
  {
    name: "SamsungPay V3 ROU",
    slug: "samsung-pay-v3-rou",
    category: "Mobile",
    componentName: "SamsungPayV3ROU",
    component: SamsungPayV3ROU,
  },
  {
    name: "SamsungPay V3 SQU",
    slug: "samsung-pay-v3-squ",
    category: "Mobile",
    componentName: "SamsungPayV3SQU",
    component: SamsungPayV3SQU,
  },
  {
    name: "SarawakPay SVG",
    slug: "sarawak-pay-svg",
    category: "Wallet",
    componentName: "SarawakPaySVG",
    component: SarawakPaySVG,
  },
  {
    name: "SarawakPay V1 ROU",
    slug: "sarawak-pay-v1-rou",
    category: "Wallet",
    componentName: "SarawakPayV1ROU",
    component: SarawakPayV1ROU,
  },
  {
    name: "SarawakPay V1 SQU",
    slug: "sarawak-pay-v1-squ",
    category: "Wallet",
    componentName: "SarawakPayV1SQU",
    component: SarawakPayV1SQU,
  },
  {
    name: "SarawakPay V2 ROU",
    slug: "sarawak-pay-v2-rou",
    category: "Wallet",
    componentName: "SarawakPayV2ROU",
    component: SarawakPayV2ROU,
  },
  {
    name: "SarawakPay V2 SQU",
    slug: "sarawak-pay-v2-squ",
    category: "Wallet",
    componentName: "SarawakPayV2SQU",
    component: SarawakPayV2SQU,
  },
  {
    name: "Senheng SVG",
    slug: "senheng-svg",
    category: "Wallet",
    componentName: "SenhengSVG",
    component: SenhengSVG,
  },
  {
    name: "Senheng V1 ROU",
    slug: "senheng-v1-rou",
    category: "Wallet",
    componentName: "SenhengV1ROU",
    component: SenhengV1ROU,
  },
  {
    name: "Senheng V1 SQU",
    slug: "senheng-v1-squ",
    category: "Wallet",
    componentName: "SenhengV1SQU",
    component: SenhengV1SQU,
  },
  {
    name: "Senheng V2 ROU",
    slug: "senheng-v2-rou",
    category: "Wallet",
    componentName: "SenhengV2ROU",
    component: SenhengV2ROU,
  },
  {
    name: "Senheng V2 SQU",
    slug: "senheng-v2-squ",
    category: "Wallet",
    componentName: "SenhengV2SQU",
    component: SenhengV2SQU,
  },
  {
    name: "Setel SVG",
    slug: "setel-svg",
    category: "Wallet",
    componentName: "SetelSVG",
    component: SetelSVG,
  },
  {
    name: "Setel V1 ROU",
    slug: "setel-v1-rou",
    category: "Wallet",
    componentName: "SetelV1ROU",
    component: SetelV1ROU,
  },
  {
    name: "Setel V1 SQU",
    slug: "setel-v1-squ",
    category: "Wallet",
    componentName: "SetelV1SQU",
    component: SetelV1SQU,
  },
  {
    name: "Setel V2 ROU",
    slug: "setel-v2-rou",
    category: "Wallet",
    componentName: "SetelV2ROU",
    component: SetelV2ROU,
  },
  {
    name: "Setel V2 SQU",
    slug: "setel-v2-squ",
    category: "Wallet",
    componentName: "SetelV2SQU",
    component: SetelV2SQU,
  },
  {
    name: "Setel V3 SQU",
    slug: "setel-v3-squ",
    category: "Wallet",
    componentName: "SetelV3SQU",
    component: SetelV3SQU,
  },
  {
    name: "ShopBack SVG",
    slug: "shop-back-svg",
    category: "BNPL",
    componentName: "ShopBackSVG",
    component: ShopBackSVG,
  },
  {
    name: "ShopBack V1 ROU",
    slug: "shop-back-v1-rou",
    category: "BNPL",
    componentName: "ShopBackV1ROU",
    component: ShopBackV1ROU,
  },
  {
    name: "ShopBack V1 SQU",
    slug: "shop-back-v1-squ",
    category: "BNPL",
    componentName: "ShopBackV1SQU",
    component: ShopBackV1SQU,
  },
  {
    name: "ShopBack V2 ROU",
    slug: "shop-back-v2-rou",
    category: "BNPL",
    componentName: "ShopBackV2ROU",
    component: ShopBackV2ROU,
  },
  {
    name: "ShopBack V2 SQU",
    slug: "shop-back-v2-squ",
    category: "BNPL",
    componentName: "ShopBackV2SQU",
    component: ShopBackV2SQU,
  },
  {
    name: "ShopeePay SVG",
    slug: "shopee-pay-svg",
    category: "Wallet",
    componentName: "ShopeePaySVG",
    component: ShopeePaySVG,
  },
  {
    name: "ShopeePay V1 ROU",
    slug: "shopee-pay-v1-rou",
    category: "Wallet",
    componentName: "ShopeePayV1ROU",
    component: ShopeePayV1ROU,
  },
  {
    name: "ShopeePay V1 SQU",
    slug: "shopee-pay-v1-squ",
    category: "Wallet",
    componentName: "ShopeePayV1SQU",
    component: ShopeePayV1SQU,
  },
  {
    name: "ShopeePay V2 ROU",
    slug: "shopee-pay-v2-rou",
    category: "Wallet",
    componentName: "ShopeePayV2ROU",
    component: ShopeePayV2ROU,
  },
  {
    name: "ShopeePay V2 SQU",
    slug: "shopee-pay-v2-squ",
    category: "Wallet",
    componentName: "ShopeePayV2SQU",
    component: ShopeePayV2SQU,
  },
  {
    name: "ShopeePay V3 ROU",
    slug: "shopee-pay-v3-rou",
    category: "Wallet",
    componentName: "ShopeePayV3ROU",
    component: ShopeePayV3ROU,
  },
  {
    name: "ShopeePay V3 SQU",
    slug: "shopee-pay-v3-squ",
    category: "Wallet",
    componentName: "ShopeePayV3SQU",
    component: ShopeePayV3SQU,
  },
  {
    name: "ShopeePay V4 ROU",
    slug: "shopee-pay-v4-rou",
    category: "Wallet",
    componentName: "ShopeePayV4ROU",
    component: ShopeePayV4ROU,
  },
  {
    name: "ShopeePay V4 SQU",
    slug: "shopee-pay-v4-squ",
    category: "Wallet",
    componentName: "ShopeePayV4SQU",
    component: ShopeePayV4SQU,
  },
  {
    name: "ShopeePay V5 ROU",
    slug: "shopee-pay-v5-rou",
    category: "Wallet",
    componentName: "ShopeePayV5ROU",
    component: ShopeePayV5ROU,
  },
  {
    name: "ShopeePay V5 SQU",
    slug: "shopee-pay-v5-squ",
    category: "Wallet",
    componentName: "ShopeePayV5SQU",
    component: ShopeePayV5SQU,
  },
  {
    name: "ShopeePay V6 ROU",
    slug: "shopee-pay-v6-rou",
    category: "Wallet",
    componentName: "ShopeePayV6ROU",
    component: ShopeePayV6ROU,
  },
  {
    name: "ShopeePay V6 SQU",
    slug: "shopee-pay-v6-squ",
    category: "Wallet",
    componentName: "ShopeePayV6SQU",
    component: ShopeePayV6SQU,
  },
  {
    name: "SPayLater SVG",
    slug: "spay-later-svg",
    category: "BNPL",
    componentName: "SPayLaterSVG",
    component: SPayLaterSVG,
  },
  {
    name: "SPayLater V1 LG",
    slug: "spay-later-v1-lg",
    category: "BNPL",
    componentName: "SPayLaterV1LG",
    component: SPayLaterV1LG,
  },
  {
    name: "SPayLater V1 ROU",
    slug: "spay-later-v1-rou",
    category: "BNPL",
    componentName: "SPayLaterV1ROU",
    component: SPayLaterV1ROU,
  },
  {
    name: "SPayLater V1 SQU",
    slug: "spay-later-v1-squ",
    category: "BNPL",
    componentName: "SPayLaterV1SQU",
    component: SPayLaterV1SQU,
  },
  {
    name: "SPayLater V2 LG",
    slug: "spay-later-v2-lg",
    category: "BNPL",
    componentName: "SPayLaterV2LG",
    component: SPayLaterV2LG,
  },
  {
    name: "SPayLater V2 ROU",
    slug: "spay-later-v2-rou",
    category: "BNPL",
    componentName: "SPayLaterV2ROU",
    component: SPayLaterV2ROU,
  },
  {
    name: "SPayLater V2 SQU",
    slug: "spay-later-v2-squ",
    category: "BNPL",
    componentName: "SPayLaterV2SQU",
    component: SPayLaterV2SQU,
  },
  {
    name: "Split SVG",
    slug: "split-svg",
    category: "BNPL",
    componentName: "SplitSVG",
    component: SplitSVG,
  },
  {
    name: "Split V1 ROU",
    slug: "split-v1-rou",
    category: "BNPL",
    componentName: "SplitV1ROU",
    component: SplitV1ROU,
  },
  {
    name: "Split V1 SQU",
    slug: "split-v1-squ",
    category: "BNPL",
    componentName: "SplitV1SQU",
    component: SplitV1SQU,
  },
  {
    name: "Split V2 ROU",
    slug: "split-v2-rou",
    category: "BNPL",
    componentName: "SplitV2ROU",
    component: SplitV2ROU,
  },
  {
    name: "Split V2 SQU",
    slug: "split-v2-squ",
    category: "BNPL",
    componentName: "SplitV2SQU",
    component: SplitV2SQU,
  },
  {
    name: "Split V3 ROU",
    slug: "split-v3-rou",
    category: "BNPL",
    componentName: "SplitV3ROU",
    component: SplitV3ROU,
  },
  {
    name: "Split V3 SQU",
    slug: "split-v3-squ",
    category: "BNPL",
    componentName: "SplitV3SQU",
    component: SplitV3SQU,
  },
  {
    name: "Split V4 ROU",
    slug: "split-v4-rou",
    category: "BNPL",
    componentName: "SplitV4ROU",
    component: SplitV4ROU,
  },
  {
    name: "Split V4 SQU",
    slug: "split-v4-squ",
    category: "BNPL",
    componentName: "SplitV4SQU",
    component: SplitV4SQU,
  },
  {
    name: "StandardChartered SVG",
    slug: "standard-chartered-svg",
    category: "Banks",
    componentName: "StandardCharteredSVG",
    component: StandardCharteredSVG,
  },
  {
    name: "StandardChartered V1 BSQU",
    slug: "standard-chartered-v1-bsqu",
    category: "Banks",
    componentName: "StandardCharteredV1BSQU",
    component: StandardCharteredV1BSQU,
  },
  {
    name: "StandardChartered V1 LG",
    slug: "standard-chartered-v1-lg",
    category: "Banks",
    componentName: "StandardCharteredV1LG",
    component: StandardCharteredV1LG,
  },
  {
    name: "StandardChartered V1 ROU",
    slug: "standard-chartered-v1-rou",
    category: "Banks",
    componentName: "StandardCharteredV1ROU",
    component: StandardCharteredV1ROU,
  },
  {
    name: "StandardChartered V1 SQU",
    slug: "standard-chartered-v1-squ",
    category: "Banks",
    componentName: "StandardCharteredV1SQU",
    component: StandardCharteredV1SQU,
  },
  {
    name: "TaPay SVG",
    slug: "ta-pay-svg",
    category: "Wallet",
    componentName: "TaPaySVG",
    component: TaPaySVG,
  },
  {
    name: "TaPay V1 ROU",
    slug: "ta-pay-v1-rou",
    category: "Wallet",
    componentName: "TaPayV1ROU",
    component: TaPayV1ROU,
  },
  {
    name: "TaPay V1 SQU",
    slug: "ta-pay-v1-squ",
    category: "Wallet",
    componentName: "TaPayV1SQU",
    component: TaPayV1SQU,
  },
  {
    name: "TaPay V2 ROU",
    slug: "ta-pay-v2-rou",
    category: "Wallet",
    componentName: "TaPayV2ROU",
    component: TaPayV2ROU,
  },
  {
    name: "TaPay V2 SQU",
    slug: "ta-pay-v2-squ",
    category: "Wallet",
    componentName: "TaPayV2SQU",
    component: TaPayV2SQU,
  },
  {
    name: "TNG SVG",
    slug: "tng-svg",
    category: "Wallet",
    componentName: "TNGSVG",
    component: TNGSVG,
  },
  {
    name: "TNG V1 ROU",
    slug: "tng-v1-rou",
    category: "Wallet",
    componentName: "TNGV1ROU",
    component: TNGV1ROU,
  },
  {
    name: "TNG V1 SQU",
    slug: "tng-v1-squ",
    category: "Wallet",
    componentName: "TNGV1SQU",
    component: TNGV1SQU,
  },
  {
    name: "TNG V2 ROU",
    slug: "tng-v2-rou",
    category: "Wallet",
    componentName: "TNGV2ROU",
    component: TNGV2ROU,
  },
  {
    name: "TNG V2 SQU",
    slug: "tng-v2-squ",
    category: "Wallet",
    componentName: "TNGV2SQU",
    component: TNGV2SQU,
  },
  {
    name: "TNG V2 SVG",
    slug: "tng-v2-svg",
    category: "Wallet",
    componentName: "TNGV2SVG",
    component: TNGV2SVG,
  },
  {
    name: "Truemoney SVG",
    slug: "truemoney-svg",
    category: "Wallet",
    componentName: "TruemoneySVG",
    component: TruemoneySVG,
  },
  {
    name: "Truemoney V1 ROU",
    slug: "truemoney-v1-rou",
    category: "Wallet",
    componentName: "TruemoneyV1ROU",
    component: TruemoneyV1ROU,
  },
  {
    name: "Truemoney V1 SQU",
    slug: "truemoney-v1-squ",
    category: "Wallet",
    componentName: "TruemoneyV1SQU",
    component: TruemoneyV1SQU,
  },
  {
    name: "Truemoney V2 ROU",
    slug: "truemoney-v2-rou",
    category: "Wallet",
    componentName: "TruemoneyV2ROU",
    component: TruemoneyV2ROU,
  },
  {
    name: "Truemoney V2 SQU",
    slug: "truemoney-v2-squ",
    category: "Wallet",
    componentName: "TruemoneyV2SQU",
    component: TruemoneyV2SQU,
  },
  {
    name: "UNIONPAY SVG",
    slug: "unionpay-svg",
    category: "Card",
    componentName: "UNIONPAYSVG",
    component: UNIONPAYSVG,
  },
  {
    name: "UNIONPAY V1 ROU",
    slug: "unionpay-v1-rou",
    category: "Card",
    componentName: "UNIONPAYV1ROU",
    component: UNIONPAYV1ROU,
  },
  {
    name: "UNIONPAY V1 SQU",
    slug: "unionpay-v1-squ",
    category: "Card",
    componentName: "UNIONPAYV1SQU",
    component: UNIONPAYV1SQU,
  },
  {
    name: "UNIONPAY V1 TRSP",
    slug: "unionpay-v1-trsp",
    category: "Card",
    componentName: "UNIONPAYV1TRSP",
    component: UNIONPAYV1TRSP,
  },
  {
    name: "UOB SVG",
    slug: "uob-svg",
    category: "Banks",
    componentName: "UOBSVG",
    component: UOBSVG,
  },
  {
    name: "UOB V1 BSQU",
    slug: "uob-v1-bsqu",
    category: "Banks",
    componentName: "UOBV1BSQU",
    component: UOBV1BSQU,
  },
  {
    name: "UOB V1 LG",
    slug: "uob-v1-lg",
    category: "Banks",
    componentName: "UOBV1LG",
    component: UOBV1LG,
  },
  {
    name: "UOB V1 ROU",
    slug: "uob-v1-rou",
    category: "Banks",
    componentName: "UOBV1ROU",
    component: UOBV1ROU,
  },
  {
    name: "UOB V1 SQU",
    slug: "uob-v1-squ",
    category: "Banks",
    componentName: "UOBV1SQU",
    component: UOBV1SQU,
  },
  {
    name: "UOB V2 BSQU",
    slug: "uob-v2-bsqu",
    category: "Banks",
    componentName: "UOBV2BSQU",
    component: UOBV2BSQU,
  },
  {
    name: "UOB V2 LG",
    slug: "uob-v2-lg",
    category: "Banks",
    componentName: "UOBV2LG",
    component: UOBV2LG,
  },
  {
    name: "UOB V2 ROU",
    slug: "uob-v2-rou",
    category: "Banks",
    componentName: "UOBV2ROU",
    component: UOBV2ROU,
  },
  {
    name: "UOB V2 SQU",
    slug: "uob-v2-squ",
    category: "Banks",
    componentName: "UOBV2SQU",
    component: UOBV2SQU,
  },
  {
    name: "UOB V3 ROU",
    slug: "uob-v3-rou",
    category: "Banks",
    componentName: "UOBV3ROU",
    component: UOBV3ROU,
  },
  {
    name: "UOB V3 SQU",
    slug: "uob-v3-squ",
    category: "Banks",
    componentName: "UOBV3SQU",
    component: UOBV3SQU,
  },
  {
    name: "UOB V4 ROU",
    slug: "uob-v4-rou",
    category: "Banks",
    componentName: "UOBV4ROU",
    component: UOBV4ROU,
  },
  {
    name: "UOB V4 SQU",
    slug: "uob-v4-squ",
    category: "Banks",
    componentName: "UOBV4SQU",
    component: UOBV4SQU,
  },
  {
    name: "VISA SVG",
    slug: "visa-svg",
    category: "Card",
    componentName: "VISASVG",
    component: VISASVG,
  },
  {
    name: "VISA V1 ROU",
    slug: "visa-v1-rou",
    category: "Card",
    componentName: "VISAV1ROU",
    component: VISAV1ROU,
  },
  {
    name: "VISA V1 SQU",
    slug: "visa-v1-squ",
    category: "Card",
    componentName: "VISAV1SQU",
    component: VISAV1SQU,
  },
  {
    name: "VISA V1 TRSP",
    slug: "visa-v1-trsp",
    category: "Card",
    componentName: "VISAV1TRSP",
    component: VISAV1TRSP,
  },
  {
    name: "VISA V2 ROU",
    slug: "visa-v2-rou",
    category: "Card",
    componentName: "VISAV2ROU",
    component: VISAV2ROU,
  },
  {
    name: "VISA V2 SQU",
    slug: "visa-v2-squ",
    category: "Card",
    componentName: "VISAV2SQU",
    component: VISAV2SQU,
  },
  {
    name: "VISA V2 TRSP",
    slug: "visa-v2-trsp",
    category: "Card",
    componentName: "VISAV2TRSP",
    component: VISAV2TRSP,
  },
  {
    name: "WeChat SVG",
    slug: "we-chat-svg",
    category: "Wallet",
    componentName: "WeChatSVG",
    component: WeChatSVG,
  },
  {
    name: "WeChat V1 ROU",
    slug: "we-chat-v1-rou",
    category: "Wallet",
    componentName: "WeChatV1ROU",
    component: WeChatV1ROU,
  },
  {
    name: "WeChat V1 SQU",
    slug: "we-chat-v1-squ",
    category: "Wallet",
    componentName: "WeChatV1SQU",
    component: WeChatV1SQU,
  },
  {
    name: "WeChat V2 ROU",
    slug: "we-chat-v2-rou",
    category: "Wallet",
    componentName: "WeChatV2ROU",
    component: WeChatV2ROU,
  },
  {
    name: "WeChat V2 SQU",
    slug: "we-chat-v2-squ",
    category: "Wallet",
    componentName: "WeChatV2SQU",
    component: WeChatV2SQU,
  },
  {
    name: "WeChat V3 ROU",
    slug: "we-chat-v3-rou",
    category: "Wallet",
    componentName: "WeChatV3ROU",
    component: WeChatV3ROU,
  },
  {
    name: "WeChat V3 SQU",
    slug: "we-chat-v3-squ",
    category: "Wallet",
    componentName: "WeChatV3SQU",
    component: WeChatV3SQU,
  },
  {
    name: "Zapp SVG",
    slug: "zapp-svg",
    category: "Wallet",
    componentName: "ZappSVG",
    component: ZappSVG,
  },
  {
    name: "Zapp V1 ROU",
    slug: "zapp-v1-rou",
    category: "Wallet",
    componentName: "ZappV1ROU",
    component: ZappV1ROU,
  },
  {
    name: "Zapp V1 SQU",
    slug: "zapp-v1-squ",
    category: "Wallet",
    componentName: "ZappV1SQU",
    component: ZappV1SQU,
  },
] as const;
